-- -----------------------------------------------------
-- Table `DB_EMBED_CONFIG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_EMBED_CONFIG` ;

CREATE  TABLE IF NOT EXISTS `DB_EMBED_CONFIG` (
	`GROUP_CODE` VARCHAR(100) NOT NULL ,
	`ITEM_CODE` VARCHAR(100) NOT NULL ,
	`NUMBER_VALUE` NUMBER(20, 2) NULL ,
	`TEXT_VALUE` VARCHAR(250) NULL ,
	`DATE_VALUE` TIMESTAMP  NULL
);

INSERT INTO `DB_EMBED_CONFIG`(`GROUP_CODE`, `ITEM_CODE`, `NUMBER_VALUE`, `DATE_VALUE`) VALUES ('SYS_CFG','INIT_DB', 1, CURRENT_TIMESTAMP());

-- -----------------------------------------------------
-- Table `STOCK_MARKET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STOCK_EXCHANGE` ;

CREATE  TABLE IF NOT EXISTS `STOCK_EXCHANGE` (
	`SYMBOL` VARCHAR(100) NOT NULL ,	
	`EXCHANGE_CODE` VARCHAR(100) NOT NULL ,	
	`EXCHANGE_NAME` VARCHAR(250) NOT NULL ,
	`COMPANY_ID` NUMBER(10) NULL ,	
	`COMPANY_NAME` VARCHAR(250) NULL ,
	`COMPANY_FULL_NAME` VARCHAR(250) NULL ,
	`ABB_NAME` VARCHAR(250) NULL ,
	`FIRST_TRADING_DATE` DATE NULL ,
	`INDUSTRY_CODE` VARCHAR(100) NULL ,
	`INDUSTRY_GROUP_CODE` VARCHAR(100) NULL ,
	`SECTOR_CODE` VARCHAR(100) NULL ,
	`SECTOR_GROUP_CODE` VARCHAR(100) NULL,
	PRIMARY KEY (`SYMBOL`) 
);

DROP INDEX IF EXISTS IDX_STOCK_MARKET_SYMBOL;
CREATE INDEX IDX_STOCK_MARKET_SYMBOL ON STOCK_EXCHANGE(`SYMBOL`);

DROP INDEX IF EXISTS IDX_STOCK_MARKET_EXCHANGE_CODE;
CREATE INDEX IDX_STOCK_MARKET_EXCHANGE_CODE ON STOCK_EXCHANGE(`EXCHANGE_CODE`);

-- -----------------------------------------------------
-- Table `ITEM_CODE_REF` for
-- COMPANY_ITEM_CALC_VIEW
-- INDUSTRY_CALC_VIEW
-- SECTOR_CALC_VIEW
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITEM_CODE_REF` ;

CREATE  TABLE IF NOT EXISTS `ITEM_CODE_REF` (
	`GROUP_CODE` VARCHAR(100) NOT NULL ,	
	`ITEM_CODE` VARCHAR(100) NOT NULL ,	
	`ITEM_NAME` VARCHAR(250) NOT NULL ,
	`LOCALE` VARCHAR(20) NOT NULL
);

DROP INDEX IF EXISTS IDX_ITEM_CODE_REF_GROUP_CODE;
CREATE INDEX IDX_ITEM_CODE_REF_GROUP_CODE ON ITEM_CODE_REF(`GROUP_CODE`);

DROP INDEX IF EXISTS IDX_ITEM_CODE_REF_LOCALE;
CREATE INDEX IDX_ITEM_CODE_REF_LOCALE ON ITEM_CODE_REF(`LOCALE`);

-- -----------------------------------------------------
-- Table `COMPANY_ITEM_CALC_VIEW `
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COMPANY_ITEM_CALC_VIEW` ;

CREATE  TABLE IF NOT EXISTS `COMPANY_ITEM_CALC_VIEW` (
  `SYMBOL` VARCHAR(100) NOT NULL ,
  `ITEM_CODE` VARCHAR(20) NULL ,
  `TEXT_VALUE` VARCHAR(30) NULL ,
  `NUMERIC_VALUE` NUMBER(30,4) NULL,
  `TRANS_DATE` TIMESTAMP NULL
);

DROP INDEX IF EXISTS IDX_COMPANY_ITEM_CALC_VIEW_SYMBOL;
CREATE INDEX IDX_COMPANY_ITEM_CALC_VIEW_SYMBOL ON COMPANY_ITEM_CALC_VIEW(`SYMBOL`);

-- -----------------------------------------------------
-- Table `INDUSTRY_ITEM_CALC_VIEW `
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INDUSTRY_ITEM_CALC_VIEW` ;

CREATE  TABLE IF NOT EXISTS `INDUSTRY_ITEM_CALC_VIEW` (
  `INDUSTRY_CODE` VARCHAR(100) NOT NULL ,
  `ITEM_CODE` VARCHAR(20) NULL ,
  `TEXT_VALUE` VARCHAR(30) NULL ,
  `NUMERIC_VALUE` NUMBER(30,4) NULL,
  `TRANS_DATE` TIMESTAMP NULL
);

DROP INDEX IF EXISTS IDX_INDUSTRY_ITEM_CALC_VIEW_INDUSTRY_CODE;
CREATE INDEX IDX_INDUSTRY_ITEM_CALC_VIEW_INDUSTRY_CODE ON INDUSTRY_ITEM_CALC_VIEW(`INDUSTRY_CODE`);

-- -----------------------------------------------------
-- Table `IFO_SECTOR_CALC_VIEW `
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SECTOR_CALC_VIEW` ;

CREATE  TABLE IF NOT EXISTS `SECTOR_CALC_VIEW` (  
  `SECTOR_CODE` VARCHAR(50) NOT NULL ,
  `PE` NUMBER(30,4) NULL,
  `PB` NUMBER(30,4) NULL,
  `SCOPE_MAKET_CAP` NUMBER(30,4) NULL,
  `SCOPE_ASSET` NUMBER(30,4) NULL,
  `SCOPE_EQUITY` NUMBER(30,4) NULL,
  `GROWTH_ASSET` NUMBER(30,4) NULL,
  `GROWTH_REVENUE` NUMBER(30,4) NULL,
  `ROA` NUMBER(30,4) NULL,
  `ROE` NUMBER(30,4) NULL,
  `PROFIT_MARGIN` NUMBER(30,4) NULL,
  `DEBT_EQUITY` NUMBER(30,4) NULL,
  `CURRENT_RATIO` NUMBER(30,4) NULL,
  `EBITDA` NUMBER(30,4) NULL,
  PRIMARY KEY (`SECTOR_CODE`)
);

DROP INDEX IF EXISTS IDX_SECTOR_CALC_VIEW_SECTOR_CODE;
CREATE INDEX IDX_SECTOR_CALC_VIEW_SECTOR_CODE ON SECTOR_CALC_VIEW(`SECTOR_CODE`);

-- -----------------------------------------------------
-- Table `IFO_INDUSTRY_CALC_VIEW `
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INDUSTRY_CALC_VIEW` ;

CREATE  TABLE IF NOT EXISTS `INDUSTRY_CALC_VIEW` (
  `INDUSTRY_CODE` VARCHAR(50) NOT NULL ,
  `SECTOR_CODE` VARCHAR(50) NOT NULL ,
  `PE` NUMBER(30,4) NULL,
  `PB` NUMBER(30,4) NULL,
  `SCOPE_MAKET_CAP` NUMBER(30,4) NULL,
  `SCOPE_ASSET` NUMBER(30,4) NULL,
  `SCOPE_EQUITY` NUMBER(30,4) NULL,
  `GROWTH_ASSET` NUMBER(30,4) NULL,
  `GROWTH_REVENUE` NUMBER(30,4) NULL,
  `ROA` NUMBER(30,4) NULL,
  `ROE` NUMBER(30,4) NULL,
  `PROFIT_MARGIN` NUMBER(30,4) NULL,
  `DEBT_EQUITY` NUMBER(30,4) NULL,
  `CURRENT_RATIO` NUMBER(30,4) NULL,
  `EBITDA` NUMBER(30,4) NULL,
  PRIMARY KEY (`INDUSTRY_CODE`)
);

DROP INDEX IF EXISTS IDX_INDUSTRY_CALC_VIEW_INDUSTRY_CODE;
CREATE INDEX IDX_INDUSTRY_CALC_VIEW_INDUSTRY_CODE ON INDUSTRY_CALC_VIEW(`INDUSTRY_CODE`);

DROP INDEX IF EXISTS IDX_INDUSTRY_CALC_VIEW_SECTOR_CODE;
CREATE INDEX IDX_INDUSTRY_CALC_VIEW_SECTOR_CODE ON INDUSTRY_CALC_VIEW(`SECTOR_CODE`);

-- -----------------------------------------------------
-- Table `COMPANY_CALC_VIEW `
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COMPANY_CALC_VIEW` ;

CREATE  TABLE IF NOT EXISTS `COMPANY_CALC_VIEW` (	
  `EXCHANGE_CODE` VARCHAR(50) NOT NULL ,
  `SEC_CODE` VARCHAR(50) NOT NULL ,
  `INDUSTRY_CODE` VARCHAR(50) NOT NULL ,
  `SECTOR_CODE` VARCHAR(50) NOT NULL ,
  `PE` NUMBER(30,4) NULL,
  `PB` NUMBER(30,4) NULL,
  `SCOPE_MAKET_CAP` NUMBER(30,4) NULL,
  `SCOPE_ASSET` NUMBER(30,4) NULL,
  `SCOPE_EQUITY` NUMBER(30,4) NULL,
  `GROWTH_ASSET` NUMBER(30,4) NULL,
  `GROWTH_REVENUE` NUMBER(30,4) NULL,
  `ROA` NUMBER(30,4) NULL,
  `ROE` NUMBER(30,4) NULL,
  `PROFIT_MARGIN` NUMBER(30,4) NULL,
  `DEBT_EQUITY` NUMBER(30,4) NULL,
  `CURRENT_RATIO` NUMBER(30,4) NULL,
  `EBITDA` NUMBER(30,4) NULL,
  PRIMARY KEY (`SEC_CODE`)
);

DROP INDEX IF EXISTS IDX_COMPANY_CALC_VIEW_SEC_CODE;
CREATE INDEX IDX_COMPANY_CALC_VIEW_SEC_CODE ON COMPANY_CALC_VIEW(`SEC_CODE`);

DROP INDEX IF EXISTS IDX_COMPANY_CALC_VIEW_INDUSTRY_CODE;
CREATE INDEX IDX_COMPANY_CALC_VIEW_INDUSTRY_CODE ON COMPANY_CALC_VIEW(`INDUSTRY_CODE`);

DROP INDEX IF EXISTS IDX_COMPANY_CALC_VIEW_SECTOR_CODE;
CREATE INDEX IDX_COMPANY_CALC_VIEW_SECTOR_CODE ON COMPANY_CALC_VIEW(`SECTOR_CODE`);

-- -----------------------------------------------------
-- Table `SEC_LAST_PRICE_VIEW `
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEC_LAST_PRICE_VIEW` ;

CREATE  TABLE IF NOT EXISTS `SEC_LAST_PRICE_VIEW` (	
  `COMPANY_ID` NUMBER(10) NULL ,
  `SYMBOL` VARCHAR(50) NOT NULL ,
  `EXCHANGE_CODE` VARCHAR(50) NOT NULL ,
  `OPEN_PRICE` NUMBER(30,4) NULL,
  `HIGH_PRICE` NUMBER(30,4) NULL,
  `LOW_PRICE` NUMBER(30,4) NULL,
  `CLOSE_PRICE` NUMBER(30,4) NULL,
  `AVERAGE_PRICE` NUMBER(30,4) NULL,
  `VOLUME` NUMBER(20) NULL,
  `AD_OPEN_PRICE` NUMBER(30,4) NULL,
  `AD_HIGH_PRICE` NUMBER(30,4) NULL,
  `AD_LOW_PRICE` NUMBER(30,4) NULL,
  `AD_CLOSE_PRICE` NUMBER(30,4) NULL,
  `AD_AVERAGE_PRICE` NUMBER(30,4) NULL,  
  `RIGHTS_TYPE` VARCHAR2(50) NULL,
  `TRANS_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`SYMBOL`)
);

DROP INDEX IF EXISTS IDX_SEC_LAST_PRICE_VIEW_SYMBOL;
CREATE INDEX IDX_SEC_LAST_PRICE_VIEW_SYMBOL ON SEC_LAST_PRICE_VIEW(`SYMBOL`);


--- -----------------------------------------------------
--- Create COMPANY_ITEM_CALC_VIEW_TEMP table from filter.company_view
--- -----------------------------------------------------
DROP TABLE IF EXISTS `COMPANY_ITEM_CALC_VIEW_TEMP` ;

CREATE  TABLE IF NOT EXISTS `COMPANY_ITEM_CALC_VIEW_TEMP` (	
	`company_id`   NUMBER(10),
	`symbol`   VARCHAR(20),
	`industry_code`   VARCHAR(20),
	`sector_code`   VARCHAR(20),
	`exchange_code`   VARCHAR(20),
	`close_price` NUMBER(20,4) NULL DEFAULT 0,
	`pct_above_52_week_low`   NUMBER(30,4) NULL DEFAULT 0,
	`pct_below_52_week_high`   NUMBER(30,4) NULL DEFAULT 0,
	
	`vs_sma_13_day`   NUMBER(30,4) NULL DEFAULT 0,
	`vs_sma_50_day`   NUMBER(30,4) NULL DEFAULT 0,
		
	`f21001`   NUMBER(30,4) NULL DEFAULT 0,
	`f23000`   NUMBER(30,4) NULL DEFAULT 0,
	`f51001`   NUMBER(30,4) NULL DEFAULT 0,
	`f51002`   NUMBER(30,4) NULL DEFAULT 0,
	`f51003`   NUMBER(30,4) NULL DEFAULT 0,
	`f51004`   NUMBER(30,4) NULL DEFAULT 0,
	`f51007`   NUMBER(30,4) NULL DEFAULT 0,
	`f51009`   NUMBER(30,4) NULL DEFAULT 0,
	`f51010`   NUMBER(30,4) NULL DEFAULT 0,
	`f51011`   NUMBER(30,4) NULL DEFAULT 0,
	`f51012`   NUMBER(30,4) NULL DEFAULT 0,
	`f51016`   NUMBER(30,4) NULL DEFAULT 0,
	`f51005`   NUMBER(30,4) NULL DEFAULT 0,
	`f52001`   NUMBER(30,4) NULL DEFAULT 0,
	`f52002`   NUMBER(30,4) NULL DEFAULT 0,
	`f53007`   NUMBER(30,4) NULL DEFAULT 0,
	`f53003`   NUMBER(30,4) NULL DEFAULT 0,
	`f53004`   NUMBER(30,4) NULL DEFAULT 0,
	`f53006`   NUMBER(30,4) NULL DEFAULT 0,
	`f53009`   NUMBER(30,4) NULL DEFAULT 0,
	`f53011`   NUMBER(30,4) NULL DEFAULT 0,
	`f53014`   NUMBER(30,4) NULL DEFAULT 0,
	`f53030`   NUMBER(30,4) NULL DEFAULT 0,
	`f53033`   NUMBER(30,4) NULL DEFAULT 0,
	`f53039`   NUMBER(30,4) NULL DEFAULT 0,
	`f53050`   NUMBER(30,4) NULL DEFAULT 0,
	`f56002`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000001`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000002`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000003`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000004`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000005`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000006`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000007`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000008`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000009`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000010`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000011`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000012`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000013`   NUMBER(30,4) NULL DEFAULT 0,
	`f51006`   NUMBER(30,4) NULL DEFAULT 0,
	`f14100`   NUMBER(30,4) NULL DEFAULT 0,
	`f12700`   NUMBER(30,4) NULL DEFAULT 0,
	PRIMARY KEY (`symbol`)
);

DROP INDEX IF EXISTS IDX_COMPANY_ITEM_CALC_VIEW_TEMP_SYMBOL;
CREATE INDEX IDX_COMPANY_ITEM_CALC_VIEW_TEMP_SYMBOL ON COMPANY_ITEM_CALC_VIEW_TEMP(`SYMBOL`);

--- -----------------------------------------------------
--- Create INDUSTRY_ITEM_CALC_VIEW_TEMP table from filter.company_view
--- -----------------------------------------------------
DROP TABLE IF EXISTS `INDUSTRY_ITEM_CALC_VIEW_TEMP` ;

CREATE  TABLE IF NOT EXISTS `INDUSTRY_ITEM_CALC_VIEW_TEMP` (	
	`industry_code`   VARCHAR(20),
	
	`f81003`   NUMBER(30,4) NULL DEFAULT 0,
	`f81005`   NUMBER(30,4) NULL DEFAULT 0,
	`f81006`   NUMBER(30,4) NULL DEFAULT 0,
	`f81011`   NUMBER(30,4) NULL DEFAULT 0,
	`f82001`   NUMBER(30,4) NULL DEFAULT 0,
	`f82002`   NUMBER(30,4) NULL DEFAULT 0,
	`f82700`   NUMBER(30,4) NULL DEFAULT 0,
	`f83000`   NUMBER(30,4) NULL DEFAULT 0,
	`f83006`   NUMBER(30,4) NULL DEFAULT 0,
	`f83030`   NUMBER(30,4) NULL DEFAULT 0,
	`f83050`   NUMBER(30,4) NULL DEFAULT 0,
	`f84000`   NUMBER(30,4) NULL DEFAULT 0,
	`f86002`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000014`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000015`   NUMBER(30,4) NULL DEFAULT 0,
	`f1000016`   NUMBER(30,4) NULL DEFAULT 0,
	PRIMARY KEY (`industry_code`)
);

DROP INDEX IF EXISTS IDX_INDUSTRY_ITEM_CALC_VIEW_TEMP_INDUSTRY_CODE;
CREATE INDEX IDX_INDUSTRY_ITEM_CALC_VIEW_TEMP_INDUSTRY_CODE ON INDUSTRY_ITEM_CALC_VIEW_TEMP(`INDUSTRY_CODE`);
