package vn.com.vndirect.domain;

/**
 * IfoBalancesheetView generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoBalancesheetView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoBalancesheetViewId id;

	// Constructors

	/** default constructor */
	public IfoBalancesheetView() {
	}

	// Property accessors

	public IfoBalancesheetViewId getId() {
		return this.id;
	}

	public void setId(IfoBalancesheetViewId id) {
		this.id = id;
	}

}