package vn.com.vndirect.domain;

/**
 * IfoBreakdownViewId generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoBreakdownViewId extends BaseBean implements java.io.Serializable {
	// Fields
	private Long companyId;
	private Double stateOwnership;
	private Double internalManagement;
	private Double strategicInvestor;
	private Double foreignOwnership;
	private Double other;

	// Constructors

	/** default constructor */
	public IfoBreakdownViewId() {
	}

	/** full constructor */
	public IfoBreakdownViewId(Long companyId, Double stateOwnership, Double internalManagement, Double strategicInvestor, Double foreignOwnership, Double other) {
		this.companyId = companyId;
		this.stateOwnership = stateOwnership;
		this.internalManagement = internalManagement;
		this.strategicInvestor = strategicInvestor;
		this.foreignOwnership = foreignOwnership;
		this.other = other;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public Double getStateOwnership() {
		return this.stateOwnership;
	}

	public void setStateOwnership(Double stateOwnership) {
		this.stateOwnership = stateOwnership;
	}

	public Double getInternalManagement() {
		return this.internalManagement;
	}

	public void setInternalManagement(Double internalManagement) {
		this.internalManagement = internalManagement;
	}

	public Double getStrategicInvestor() {
		return this.strategicInvestor;
	}

	public void setStrategicInvestor(Double strategicInvestor) {
		this.strategicInvestor = strategicInvestor;
	}

	public Double getForeignOwnership() {
		return this.foreignOwnership;
	}

	public void setForeignOwnership(Double foreignOwnership) {
		this.foreignOwnership = foreignOwnership;
	}

	public Double getOther() {
		return this.other;
	}

	public void setOther(Double other) {
		this.other = other;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoBreakdownViewId))
			return false;
		IfoBreakdownViewId castOther = (IfoBreakdownViewId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getStateOwnership() == castOther.getStateOwnership()) || (this.getStateOwnership() != null && castOther.getStateOwnership() != null && this.getStateOwnership().equals(
						castOther.getStateOwnership())))
				&& ((this.getInternalManagement() == castOther.getInternalManagement()) || (this.getInternalManagement() != null && castOther.getInternalManagement() != null && this
						.getInternalManagement().equals(castOther.getInternalManagement())))
				&& ((this.getStrategicInvestor() == castOther.getStrategicInvestor()) || (this.getStrategicInvestor() != null && castOther.getStrategicInvestor() != null && this
						.getStrategicInvestor().equals(castOther.getStrategicInvestor())))
				&& ((this.getForeignOwnership() == castOther.getForeignOwnership()) || (this.getForeignOwnership() != null && castOther.getForeignOwnership() != null && this.getForeignOwnership()
						.equals(castOther.getForeignOwnership())))
				&& ((this.getOther() == castOther.getOther()) || (this.getOther() != null && castOther.getOther() != null && this.getOther().equals(castOther.getOther())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getStateOwnership() == null ? 0 : this.getStateOwnership().hashCode());
		result = 37 * result + (getInternalManagement() == null ? 0 : this.getInternalManagement().hashCode());
		result = 37 * result + (getStrategicInvestor() == null ? 0 : this.getStrategicInvestor().hashCode());
		result = 37 * result + (getForeignOwnership() == null ? 0 : this.getForeignOwnership().hashCode());
		result = 37 * result + (getOther() == null ? 0 : this.getOther().hashCode());
		return result;
	}

}