package vn.com.vndirect.domain;

/**
 * IfoBreakdownView generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoBreakdownView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoBreakdownViewId id;

	// Constructors

	/** default constructor */
	public IfoBreakdownView() {
	}

	// Property accessors

	public IfoBreakdownViewId getId() {
		return this.id;
	}

	public void setId(IfoBreakdownViewId id) {
		this.id = id;
	}

}