package vn.com.vndirect.domain;

/**
 * IfoCompanyProfileViewId generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoCompanyProfileViewId extends BaseBean implements java.io.Serializable {

	// Fields

	private Long companyId;
	private String vietnameseName;
	private String internationalName;
	private String abbreviation;
	private String headquarter;
	private String telephone;
	private String fax;
	private String website;
	private String indexMembership;
	private String sector;
	private String industry;
	private String numberOfBranches;
	private String fullEmployee;
	private String ipoInformation;
	private String ipoLocation;
	private String ipoHighestBid;
	private String ipoLowestBid;
	private String ipoAverageBid;
	private String history;
	private String mainBusiness;
	private String marketPosition;
	private String plan;
	private String locale;

	// Constructors

	/** default constructor */
	public IfoCompanyProfileViewId() {
	}

	/** full constructor */
	public IfoCompanyProfileViewId(Long companyId, String vietnameseName, String internationalName, String abbreviation, String headquarter, String telephone, String fax, String website,
			String indexMembership, String sector, String industry, String numberOfBranches, String fullEmployee, String ipoInformation, String ipoLocation, String ipoHighestBid, String ipoLowestBid,
			String ipoAverageBid) {
		this.companyId = companyId;
		this.vietnameseName = vietnameseName;
		this.internationalName = internationalName;
		this.abbreviation = abbreviation;
		this.headquarter = headquarter;
		this.telephone = telephone;
		this.fax = fax;
		this.website = website;
		this.indexMembership = indexMembership;
		this.sector = sector;
		this.industry = industry;
		this.numberOfBranches = numberOfBranches;
		this.fullEmployee = fullEmployee;
		this.ipoInformation = ipoInformation;
		this.ipoLocation = ipoLocation;
		this.ipoHighestBid = ipoHighestBid;
		this.ipoLowestBid = ipoLowestBid;
		this.ipoAverageBid = ipoAverageBid;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getVietnameseName() {
		return this.vietnameseName;
	}

	public void setVietnameseName(String vietnameseName) {
		this.vietnameseName = vietnameseName;
	}

	public String getInternationalName() {
		return this.internationalName;
	}

	public void setInternationalName(String internationalName) {
		this.internationalName = internationalName;
	}

	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public String getHeadquarter() {
		return this.headquarter;
	}

	public void setHeadquarter(String headquarter) {
		this.headquarter = headquarter;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getIndexMembership() {
		return this.indexMembership;
	}

	public void setIndexMembership(String indexMembership) {
		this.indexMembership = indexMembership;
	}

	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getNumberOfBranches() {
		return this.numberOfBranches;
	}

	public void setNumberOfBranches(String numberOfBranches) {
		this.numberOfBranches = numberOfBranches;
	}

	public String getFullEmployee() {
		return this.fullEmployee;
	}

	public void setFullEmployee(String fullEmployee) {
		this.fullEmployee = fullEmployee;
	}

	public String getIpoInformation() {
		return this.ipoInformation;
	}

	public void setIpoInformation(String ipoInformation) {
		this.ipoInformation = ipoInformation;
	}

	public String getIpoLocation() {
		return this.ipoLocation;
	}

	public void setIpoLocation(String ipoLocation) {
		this.ipoLocation = ipoLocation;
	}

	public String getIpoHighestBid() {
		return this.ipoHighestBid;
	}

	public void setIpoHighestBid(String ipoHighestBid) {
		this.ipoHighestBid = ipoHighestBid;
	}

	public String getIpoLowestBid() {
		return this.ipoLowestBid;
	}

	public void setIpoLowestBid(String ipoLowestBid) {
		this.ipoLowestBid = ipoLowestBid;
	}

	public String getIpoAverageBid() {
		return this.ipoAverageBid;
	}

	public void setIpoAverageBid(String ipoAverageBid) {
		this.ipoAverageBid = ipoAverageBid;
	}

	/**
	 * @return the history
	 */
	public String getHistory() {
		return history;
	}

	/**
	 * @param history
	 *            the history to set
	 */
	public void setHistory(String history) {
		this.history = history;
	}

	/**
	 * @return the mainBusiness
	 */
	public String getMainBusiness() {
		return mainBusiness;
	}

	/**
	 * @param mainBusiness
	 *            the mainBusiness to set
	 */
	public void setMainBusiness(String mainBusiness) {
		this.mainBusiness = mainBusiness;
	}

	/**
	 * @return the marketPosition
	 */
	public String getMarketPosition() {
		return marketPosition;
	}

	/**
	 * @param marketPosition
	 *            the marketPosition to set
	 */
	public void setMarketPosition(String marketPosition) {
		this.marketPosition = marketPosition;
	}

	/**
	 * @return the plan
	 */
	public String getPlan() {
		return plan;
	}

	/**
	 * @param plan
	 *            the plan to set
	 */
	public void setPlan(String plan) {
		this.plan = plan;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoCompanyProfileViewId))
			return false;
		IfoCompanyProfileViewId castOther = (IfoCompanyProfileViewId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getVietnameseName() == castOther.getVietnameseName()) || (this.getVietnameseName() != null && castOther.getVietnameseName() != null && this.getVietnameseName().equals(
						castOther.getVietnameseName())))
				&& ((this.getInternationalName() == castOther.getInternationalName()) || (this.getInternationalName() != null && castOther.getInternationalName() != null && this
						.getInternationalName().equals(castOther.getInternationalName())))
				&& ((this.getAbbreviation() == castOther.getAbbreviation()) || (this.getAbbreviation() != null && castOther.getAbbreviation() != null && this.getAbbreviation().equals(
						castOther.getAbbreviation())))
				&& ((this.getHeadquarter() == castOther.getHeadquarter()) || (this.getHeadquarter() != null && castOther.getHeadquarter() != null && this.getHeadquarter().equals(
						castOther.getHeadquarter())))
				&& ((this.getTelephone() == castOther.getTelephone()) || (this.getTelephone() != null && castOther.getTelephone() != null && this.getTelephone().equals(castOther.getTelephone())))
				&& ((this.getFax() == castOther.getFax()) || (this.getFax() != null && castOther.getFax() != null && this.getFax().equals(castOther.getFax())))
				&& ((this.getWebsite() == castOther.getWebsite()) || (this.getWebsite() != null && castOther.getWebsite() != null && this.getWebsite().equals(castOther.getWebsite())))
				&& ((this.getIndexMembership() == castOther.getIndexMembership()) || (this.getIndexMembership() != null && castOther.getIndexMembership() != null && this.getIndexMembership().equals(
						castOther.getIndexMembership())))
				&& ((this.getSector() == castOther.getSector()) || (this.getSector() != null && castOther.getSector() != null && this.getSector().equals(castOther.getSector())))
				&& ((this.getIndustry() == castOther.getIndustry()) || (this.getIndustry() != null && castOther.getIndustry() != null && this.getIndustry().equals(castOther.getIndustry())))
				&& ((this.getNumberOfBranches() == castOther.getNumberOfBranches()) || (this.getNumberOfBranches() != null && castOther.getNumberOfBranches() != null && this.getNumberOfBranches()
						.equals(castOther.getNumberOfBranches())))
				&& ((this.getFullEmployee() == castOther.getFullEmployee()) || (this.getFullEmployee() != null && castOther.getFullEmployee() != null && this.getFullEmployee().equals(
						castOther.getFullEmployee())))
				&& ((this.getIpoInformation() == castOther.getIpoInformation()) || (this.getIpoInformation() != null && castOther.getIpoInformation() != null && this.getIpoInformation().equals(
						castOther.getIpoInformation())))
				&& ((this.getIpoLocation() == castOther.getIpoLocation()) || (this.getIpoLocation() != null && castOther.getIpoLocation() != null && this.getIpoLocation().equals(
						castOther.getIpoLocation())))
				&& ((this.getIpoHighestBid() == castOther.getIpoHighestBid()) || (this.getIpoHighestBid() != null && castOther.getIpoHighestBid() != null && this.getIpoHighestBid().equals(
						castOther.getIpoHighestBid())))
				&& ((this.getIpoLowestBid() == castOther.getIpoLowestBid()) || (this.getIpoLowestBid() != null && castOther.getIpoLowestBid() != null && this.getIpoLowestBid().equals(
						castOther.getIpoLowestBid())))
				&& ((this.getIpoAverageBid() == castOther.getIpoAverageBid()) || (this.getIpoAverageBid() != null && castOther.getIpoAverageBid() != null && this.getIpoAverageBid().equals(
						castOther.getIpoAverageBid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getVietnameseName() == null ? 0 : this.getVietnameseName().hashCode());
		result = 37 * result + (getInternationalName() == null ? 0 : this.getInternationalName().hashCode());
		result = 37 * result + (getAbbreviation() == null ? 0 : this.getAbbreviation().hashCode());
		result = 37 * result + (getHeadquarter() == null ? 0 : this.getHeadquarter().hashCode());
		result = 37 * result + (getTelephone() == null ? 0 : this.getTelephone().hashCode());
		result = 37 * result + (getFax() == null ? 0 : this.getFax().hashCode());
		result = 37 * result + (getWebsite() == null ? 0 : this.getWebsite().hashCode());
		result = 37 * result + (getIndexMembership() == null ? 0 : this.getIndexMembership().hashCode());
		result = 37 * result + (getSector() == null ? 0 : this.getSector().hashCode());
		result = 37 * result + (getIndustry() == null ? 0 : this.getIndustry().hashCode());
		result = 37 * result + (getNumberOfBranches() == null ? 0 : this.getNumberOfBranches().hashCode());
		result = 37 * result + (getFullEmployee() == null ? 0 : this.getFullEmployee().hashCode());
		result = 37 * result + (getIpoInformation() == null ? 0 : this.getIpoInformation().hashCode());
		result = 37 * result + (getIpoLocation() == null ? 0 : this.getIpoLocation().hashCode());
		result = 37 * result + (getIpoHighestBid() == null ? 0 : this.getIpoHighestBid().hashCode());
		result = 37 * result + (getIpoLowestBid() == null ? 0 : this.getIpoLowestBid().hashCode());
		result = 37 * result + (getIpoAverageBid() == null ? 0 : this.getIpoAverageBid().hashCode());
		return result;
	}

	/**
	 * @return the locale
	 */
	public String getLocale() {
		return locale;
	}

	/**
	 * @param locale
	 *            the locale to set
	 */
	public void setLocale(String locale) {
		this.locale = locale;
	}

}