package vn.com.vndirect.domain;

/**
 * IfoCompanyDocumentId generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoCompanyDocumentId extends BaseBean implements java.io.Serializable {

	// Fields

	private Long companyId;
	private Long documentId;

	// Constructors

	/** default constructor */
	public IfoCompanyDocumentId() {
	}

	/** full constructor */
	public IfoCompanyDocumentId(Long companyId, Long documentId) {
		this.companyId = companyId;
		this.documentId = documentId;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public Long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Long documentId) {
		this.documentId = documentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoCompanyDocumentId))
			return false;
		IfoCompanyDocumentId castOther = (IfoCompanyDocumentId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getDocumentId() == castOther.getDocumentId()) || (this.getDocumentId() != null && castOther.getDocumentId() != null && this.getDocumentId().equals(castOther.getDocumentId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getDocumentId() == null ? 0 : this.getDocumentId().hashCode());
		return result;
	}

}