package vn.com.vndirect.domain;

/**
 * IfoCompanyOfficersView generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoCompanyOfficersView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoCompanyOfficersViewId id;

	// Constructors

	/** default constructor */
	public IfoCompanyOfficersView() {
	}

	// Property accessors

	public IfoCompanyOfficersViewId getId() {
		return this.id;
	}

	public void setId(IfoCompanyOfficersViewId id) {
		this.id = id;
	}

}