package vn.com.vndirect.domain;

/**
 * IfoCompanyOfficersViewId generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoCompanyOfficersViewId extends BaseBean implements java.io.Serializable {

	// Fields

	private Long companyId;
	private String name;
	private String position;
	private String locale;
	private Long displayOrder;

	// Constructors

	/** default constructor */
	public IfoCompanyOfficersViewId() {
	}

	/** full constructor */
	public IfoCompanyOfficersViewId(Long companyId, String name, String position) {
		this.companyId = companyId;
		this.name = name;
		this.position = position;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Long getDisplayOrder() {
		return displayOrder;
	}

	public void setDisplayOrder(Long displayOrder) {
		this.displayOrder = displayOrder;
	}

	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoCompanyOfficersViewId))
			return false;
		IfoCompanyOfficersViewId castOther = (IfoCompanyOfficersViewId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this.getName().equals(castOther.getName())))
				&& ((this.getPosition() == castOther.getPosition()) || (this.getPosition() != null && castOther.getPosition() != null && this.getPosition().equals(castOther.getPosition())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getPosition() == null ? 0 : this.getPosition().hashCode());
		return result;
	}

}