package vn.com.vndirect.domain;

import java.util.Date;

/**
 * IfoCompanySnapshotViewId generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoCompanySnapshotViewId extends BaseBean implements java.io.Serializable {

	// Fields

	private Long companyId;
	private String exchangeCode;
	private Double weekHigh;
	private Double weekLow;
	private Double marketCapital;
	private Double shareOutstanding;
	private Double listedShares;
	private Double declaredDividend;
	private Double dividendYield;
	private Date exDividendDate;
	private Date dividendPayableDate;
	private Double eps;
	private Double epsYear;
	private Double roa;
	private Double roe;
	private Double leverage;
	private Double earningsValue;
	private Double bookValue;
	private Double beta;
	private Double averageVolumn;
	private Double pe;
	private Double pb;
	private Double foreignOwnership;
	private Double foreignSoldVol;
	private Double foreignBoughtVol;
	private String locale;
	private String companyOverview;
	private int overviewStatus;

	// Constructors

	/** default constructor */
	public IfoCompanySnapshotViewId() {
	}

	/** full constructor */
	public IfoCompanySnapshotViewId(Long companyId, String exchangeCode, Double weekHigh, Double weekLow, Double marketCapital, Double shareOutstanding, Double listedShares, Double declaredDividend,
			Double dividendYield, Date exDividendDate, Date dividendPayableDate, Double eps, Double epsYear, Double roa, Double roe, Double leverage, Double earningsValue, Double bookValue,
			Double beta, Double averageVolumn, Double pe, Double pb, Double foreignOwnership, Double foreignSoldVol, Double foreignBoughtVol) {
		this.companyId = companyId;
		this.exchangeCode = exchangeCode;
		this.weekHigh = weekHigh;
		this.weekLow = weekLow;
		this.marketCapital = marketCapital;
		this.shareOutstanding = shareOutstanding;
		this.listedShares = listedShares;
		this.declaredDividend = declaredDividend;
		this.dividendYield = dividendYield;
		this.exDividendDate = exDividendDate;
		this.dividendPayableDate = dividendPayableDate;
		this.eps = eps;
		this.epsYear = epsYear;
		this.roa = roa;
		this.roe = roe;
		this.leverage = leverage;
		this.earningsValue = earningsValue;
		this.bookValue = bookValue;
		this.beta = beta;
		this.averageVolumn = averageVolumn;
		this.pe = pe;
		this.pb = pb;
		this.foreignOwnership = foreignOwnership;
		this.foreignSoldVol = foreignSoldVol;
		this.foreignBoughtVol = foreignBoughtVol;
	}

	public String getCompanyOverview() {
		return this.companyOverview;
	}

	public void setCompanyOverview(String companyOverview) {
		this.companyOverview = companyOverview;
	}

	/**
	 * @return the locale
	 */
	public String getLocale() {
		return locale;
	}

	/**
	 * @param locale
	 *            the locale to set
	 */
	public void setLocale(String locale) {
		this.locale = locale;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getExchangeCode() {
		return this.exchangeCode;
	}

	public void setExchangeCode(String exchangeCode) {
		this.exchangeCode = exchangeCode;
	}

	public Double getWeekHigh() {
		return this.weekHigh;
	}

	public void setWeekHigh(Double weekHigh) {
		this.weekHigh = weekHigh;
	}

	public Double getWeekLow() {
		return this.weekLow;
	}

	public void setWeekLow(Double weekLow) {
		this.weekLow = weekLow;
	}

	public Double getMarketCapital() {
		return this.marketCapital;
	}

	public void setMarketCapital(Double marketCapital) {
		this.marketCapital = marketCapital;
	}

	public Double getShareOutstanding() {
		return this.shareOutstanding;
	}

	public void setShareOutstanding(Double shareOutstanding) {
		this.shareOutstanding = shareOutstanding;
	}

	public Double getListedShares() {
		return this.listedShares;
	}

	public void setListedShares(Double listedShares) {
		this.listedShares = listedShares;
	}

	public Double getDeclaredDividend() {
		return this.declaredDividend;
	}

	public void setDeclaredDividend(Double declaredDividend) {
		this.declaredDividend = declaredDividend;
	}

	public Double getDividendYield() {
		return this.dividendYield;
	}

	public void setDividendYield(Double dividendYield) {
		this.dividendYield = dividendYield;
	}

	public Date getExDividendDate() {
		return this.exDividendDate;
	}

	public void setExDividendDate(Date exDividendDate) {
		this.exDividendDate = exDividendDate;
	}

	public Date getDividendPayableDate() {
		return this.dividendPayableDate;
	}

	public void setDividendPayableDate(Date dividendPayableDate) {
		this.dividendPayableDate = dividendPayableDate;
	}

	public Double getEps() {
		return this.eps;
	}

	public void setEps(Double eps) {
		this.eps = eps;
	}

	public Double getEpsYear() {
		return this.epsYear;
	}

	public void setEpsYear(Double epsYear) {
		this.epsYear = epsYear;
	}

	public Double getRoa() {
		return this.roa;
	}

	public void setRoa(Double roa) {
		this.roa = roa;
	}

	public Double getRoe() {
		return this.roe;
	}

	public void setRoe(Double roe) {
		this.roe = roe;
	}

	public Double getLeverage() {
		return this.leverage;
	}

	public void setLeverage(Double leverage) {
		this.leverage = leverage;
	}

	public Double getEarningsValue() {
		return this.earningsValue;
	}

	public void setEarningsValue(Double earningsValue) {
		this.earningsValue = earningsValue;
	}

	public Double getBookValue() {
		return this.bookValue;
	}

	public void setBookValue(Double bookValue) {
		this.bookValue = bookValue;
	}

	public Double getBeta() {
		return this.beta;
	}

	public void setBeta(Double beta) {
		this.beta = beta;
	}

	public Double getAverageVolumn() {
		return averageVolumn;
	}

	public void setAverageVolumn(Double averageVolumn) {
		this.averageVolumn = averageVolumn;
	}

	public Double getForeignBoughtVol() {
		return foreignBoughtVol;
	}

	public void setForeignBoughtVol(Double foreignBoughtVol) {
		this.foreignBoughtVol = foreignBoughtVol;
	}

	public Double getForeignOwnership() {
		return foreignOwnership;
	}

	public void setForeignOwnership(Double foreignOwnership) {
		this.foreignOwnership = foreignOwnership;
	}

	public Double getForeignSoldVol() {
		return foreignSoldVol;
	}

	public void setForeignSoldVol(Double foreignSoldVol) {
		this.foreignSoldVol = foreignSoldVol;
	}

	public Double getPe() {
		return pe;
	}

	public void setPe(Double pe) {
		this.pe = pe;
	}

	public Double getPb() {
		return pb;
	}

	public void setPb(Double pb) {
		this.pb = pb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoCompanySnapshotViewId))
			return false;
		IfoCompanySnapshotViewId castOther = (IfoCompanySnapshotViewId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getExchangeCode() == castOther.getExchangeCode()) || (this.getExchangeCode() != null && castOther.getExchangeCode() != null && this.getExchangeCode().equals(
						castOther.getExchangeCode())))
				&& ((this.getWeekHigh() == castOther.getWeekHigh()) || (this.getWeekHigh() != null && castOther.getWeekHigh() != null && this.getWeekHigh().equals(castOther.getWeekHigh())))
				&& ((this.getWeekLow() == castOther.getWeekLow()) || (this.getWeekLow() != null && castOther.getWeekLow() != null && this.getWeekLow().equals(castOther.getWeekLow())))
				&& ((this.getMarketCapital() == castOther.getMarketCapital()) || (this.getMarketCapital() != null && castOther.getMarketCapital() != null && this.getMarketCapital().equals(
						castOther.getMarketCapital())))
				&& ((this.getShareOutstanding() == castOther.getShareOutstanding()) || (this.getShareOutstanding() != null && castOther.getShareOutstanding() != null && this.getShareOutstanding()
						.equals(castOther.getShareOutstanding())))
				&& ((this.getListedShares() == castOther.getListedShares()) || (this.getListedShares() != null && castOther.getListedShares() != null && this.getListedShares().equals(
						castOther.getListedShares())))
				&& ((this.getDeclaredDividend() == castOther.getDeclaredDividend()) || (this.getDeclaredDividend() != null && castOther.getDeclaredDividend() != null && this.getDeclaredDividend()
						.equals(castOther.getDeclaredDividend())))
				&& ((this.getDividendYield() == castOther.getDividendYield()) || (this.getDividendYield() != null && castOther.getDividendYield() != null && this.getDividendYield().equals(
						castOther.getDividendYield())))
				&& ((this.getExDividendDate() == castOther.getExDividendDate()) || (this.getExDividendDate() != null && castOther.getExDividendDate() != null && this.getExDividendDate().equals(
						castOther.getExDividendDate())))
				&& ((this.getDividendPayableDate() == castOther.getDividendPayableDate()) || (this.getDividendPayableDate() != null && castOther.getDividendPayableDate() != null && this
						.getDividendPayableDate().equals(castOther.getDividendPayableDate())))
				&& ((this.getEps() == castOther.getEps()) || (this.getEps() != null && castOther.getEps() != null && this.getEps().equals(castOther.getEps())))
				&& ((this.getEpsYear() == castOther.getEpsYear()) || (this.getEpsYear() != null && castOther.getEpsYear() != null && this.getEpsYear().equals(castOther.getEpsYear())))
				&& ((this.getRoa() == castOther.getRoa()) || (this.getRoa() != null && castOther.getRoa() != null && this.getRoa().equals(castOther.getRoa())))
				&& ((this.getRoe() == castOther.getRoe()) || (this.getRoe() != null && castOther.getRoe() != null && this.getRoe().equals(castOther.getRoe())))
				&& ((this.getLeverage() == castOther.getLeverage()) || (this.getLeverage() != null && castOther.getLeverage() != null && this.getLeverage().equals(castOther.getLeverage())))
				&& ((this.getEarningsValue() == castOther.getEarningsValue()) || (this.getEarningsValue() != null && castOther.getEarningsValue() != null && this.getEarningsValue().equals(
						castOther.getEarningsValue())))
				&& ((this.getBookValue() == castOther.getBookValue()) || (this.getBookValue() != null && castOther.getBookValue() != null && this.getBookValue().equals(castOther.getBookValue())))
				&& ((this.getBeta() == castOther.getBeta()) || (this.getBeta() != null && castOther.getBeta() != null && this.getBeta().equals(castOther.getBeta())))
				&& ((this.getAverageVolumn() == castOther.getAverageVolumn()) || (this.getAverageVolumn() != null && castOther.getAverageVolumn() != null && this.getAverageVolumn().equals(
						castOther.getAverageVolumn())))
				&& ((this.getPe() == castOther.getPe()) || (this.getPe() != null && castOther.getPe() != null && this.getPe().equals(castOther.getPe())))
				&& ((this.getPb() == castOther.getPb()) || (this.getPb() != null && castOther.getPb() != null && this.getPb().equals(castOther.getPb())))
				&& ((this.getForeignOwnership() == castOther.getForeignOwnership()) || (this.getForeignOwnership() != null && castOther.getForeignOwnership() != null && this.getForeignOwnership()
						.equals(castOther.getForeignOwnership())))
				&& ((this.getForeignSoldVol() == castOther.getForeignSoldVol()) || (this.getForeignSoldVol() != null && castOther.getForeignSoldVol() != null && this.getForeignSoldVol().equals(
						castOther.getForeignSoldVol())))
				&& ((this.getForeignBoughtVol() == castOther.getForeignBoughtVol()) || (this.getForeignBoughtVol() != null && castOther.getForeignBoughtVol() != null && this.getForeignBoughtVol()
						.equals(castOther.getForeignBoughtVol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getExchangeCode() == null ? 0 : this.getExchangeCode().hashCode());
		result = 37 * result + (getWeekHigh() == null ? 0 : this.getWeekHigh().hashCode());
		result = 37 * result + (getWeekLow() == null ? 0 : this.getWeekLow().hashCode());
		result = 37 * result + (getMarketCapital() == null ? 0 : this.getMarketCapital().hashCode());
		result = 37 * result + (getShareOutstanding() == null ? 0 : this.getShareOutstanding().hashCode());
		result = 37 * result + (getListedShares() == null ? 0 : this.getListedShares().hashCode());
		result = 37 * result + (getDeclaredDividend() == null ? 0 : this.getDeclaredDividend().hashCode());
		result = 37 * result + (getDividendYield() == null ? 0 : this.getDividendYield().hashCode());
		result = 37 * result + (getExDividendDate() == null ? 0 : this.getExDividendDate().hashCode());
		result = 37 * result + (getDividendPayableDate() == null ? 0 : this.getDividendPayableDate().hashCode());
		result = 37 * result + (getEps() == null ? 0 : this.getEps().hashCode());
		result = 37 * result + (getEpsYear() == null ? 0 : this.getEpsYear().hashCode());
		result = 37 * result + (getRoa() == null ? 0 : this.getRoa().hashCode());
		result = 37 * result + (getRoe() == null ? 0 : this.getRoe().hashCode());
		result = 37 * result + (getLeverage() == null ? 0 : this.getLeverage().hashCode());
		result = 37 * result + (getEarningsValue() == null ? 0 : this.getEarningsValue().hashCode());
		result = 37 * result + (getBookValue() == null ? 0 : this.getBookValue().hashCode());
		result = 37 * result + (getBeta() == null ? 0 : this.getBeta().hashCode());
		result = 37 * result + (getAverageVolumn() == null ? 0 : this.getAverageVolumn().hashCode());
		result = 37 * result + (getPe() == null ? 0 : this.getPe().hashCode());
		result = 37 * result + (getPb() == null ? 0 : this.getPb().hashCode());
		result = 37 * result + (getForeignOwnership() == null ? 0 : this.getForeignOwnership().hashCode());
		result = 37 * result + (getForeignSoldVol() == null ? 0 : this.getForeignSoldVol().hashCode());
		result = 37 * result + (getForeignBoughtVol() == null ? 0 : this.getForeignBoughtVol().hashCode());
		return result;
	}

	/**
	 * @return the overviewStatus
	 */
	public int getOverviewStatus() {
		return overviewStatus;
	}

	/**
	 * @param overviewStatus
	 *            the overviewStatus to set
	 */
	public void setOverviewStatus(int overviewStatus) {
		this.overviewStatus = overviewStatus;
	}

}