package vn.com.vndirect.domain;

/**
 * IfoCompanySnapshotView generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoCompanySnapshotView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoCompanySnapshotViewId id;

	// Constructors

	/** default constructor */
	public IfoCompanySnapshotView() {
	}

	// Property accessors

	public IfoCompanySnapshotViewId getId() {
		return this.id;
	}

	public void setId(IfoCompanySnapshotViewId id) {
		this.id = id;
	}

}