package vn.com.vndirect.domain;

/**
 * IfoCashflowView generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoCashflowView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoCashflowViewId id;

	// Constructors

	/** default constructor */
	public IfoCashflowView() {
	}

	// Property accessors

	public IfoCashflowViewId getId() {
		return this.id;
	}

	public void setId(IfoCashflowViewId id) {
		this.id = id;
	}

}