package vn.com.vndirect.domain;

/**
 * IfoCompanyProfileView generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoCompanyProfileView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoCompanyProfileViewId id;

	// Constructors

	/** default constructor */
	public IfoCompanyProfileView() {
	}

	// Property accessors

	public IfoCompanyProfileViewId getId() {
		return this.id;
	}

	public void setId(IfoCompanyProfileViewId id) {
		this.id = id;
	}

}