package vn.com.vndirect.domain;

import java.util.Date;

/**
 * IfoCompanyDocument generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoCompanyDocument extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoCompanyDocumentId id;
	private IfoDocument ifoDocument;
	private IfoCompany ifoCompany;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;

	// Constructors

	/** default constructor */
	public IfoCompanyDocument() {
	}

	/** minimal constructor */
	public IfoCompanyDocument(IfoCompanyDocumentId id, IfoDocument ifoDocument, IfoCompany ifoCompany) {
		this.id = id;
		this.ifoDocument = ifoDocument;
		this.ifoCompany = ifoCompany;
	}

	/** full constructor */
	public IfoCompanyDocument(IfoCompanyDocumentId id, IfoDocument ifoDocument, IfoCompany ifoCompany, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
		this.id = id;
		this.ifoDocument = ifoDocument;
		this.ifoCompany = ifoCompany;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	// Property accessors

	public IfoCompanyDocumentId getId() {
		return this.id;
	}

	public void setId(IfoCompanyDocumentId id) {
		this.id = id;
	}

	public IfoDocument getIfoDocument() {
		return this.ifoDocument;
	}

	public void setIfoDocument(IfoDocument ifoDocument) {
		this.ifoDocument = ifoDocument;
	}

	public IfoCompany getIfoCompany() {
		return this.ifoCompany;
	}

	public void setIfoCompany(IfoCompany ifoCompany) {
		this.ifoCompany = ifoCompany;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}