package vn.com.vndirect.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import vn.com.web.commons.utility.DateUtils;

/**
 * IfoDocument generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings({ "unchecked", "serial" })
public class IfoDocument extends BaseBean implements java.io.Serializable {

	/**
	 * 
	 */
	// Fields
	private Long documentId;
	private IfoAccessType ifoAccessType;
	private String documentType;
	private String title;
	private String contributor;
	private String author;
	private Date releasedDate;
	private String abstract_;
	private String fileName;
	private String filePath;
	private String status;
	private Long accessLevel;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private String locale;
	private String symbol;
	private Set ifoCompanyDocuments = new HashSet(0);

	// Constructors

	/** default constructor */
	public IfoDocument() {
	}

	/** minimal constructor */
	public IfoDocument(IfoAccessType ifoAccessType, String documentType, String fileName) {
		this.ifoAccessType = ifoAccessType;
		this.documentType = documentType;
		this.fileName = fileName;
	}

	/** full constructor */
	public IfoDocument(IfoAccessType ifoAccessType, String documentType, String title, String contributor, String author,
			Date releasedDate, String abstract_, String fileName, String filePath, String status, Long accessLevel,
			Date createdDate, String createdBy, Date modifiedDate, String modifiedBy, String locale, Set ifoCompanyDocuments) {
		this.ifoAccessType = ifoAccessType;
		this.documentType = documentType;
		this.title = title;
		this.contributor = contributor;
		this.author = author;
		this.releasedDate = releasedDate;
		this.abstract_ = abstract_;
		this.fileName = fileName;
		this.filePath = filePath;
		this.status = status;
		this.accessLevel = accessLevel;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.locale = locale;
		this.ifoCompanyDocuments = ifoCompanyDocuments;
	}

	// Property accessors

	public Long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Long documentId) {
		this.documentId = documentId;
	}

	public IfoAccessType getIfoAccessType() {
		return this.ifoAccessType;
	}

	public void setIfoAccessType(IfoAccessType ifoAccessType) {
		this.ifoAccessType = ifoAccessType;
	}

	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContributor() {
		return this.contributor;
	}

	public void setContributor(String contributor) {
		this.contributor = contributor;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public Date getReleasedDate() {
		return this.releasedDate;
	}

	public void setReleasedDate(Date releasedDate) {
		this.releasedDate = releasedDate;
	}

	public String getAbstract_() {
		return this.abstract_;
	}

	public void setAbstract_(String abstract_) {
		this.abstract_ = abstract_;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getAccessLevel() {
		return this.accessLevel;
	}

	public void setAccessLevel(Long accessLevel) {
		this.accessLevel = accessLevel;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set getIfoCompanyDocuments() {
		return this.ifoCompanyDocuments;
	}

	public void setIfoCompanyDocuments(Set ifoCompanyDocuments) {
		this.ifoCompanyDocuments = ifoCompanyDocuments;
	}

	public String getStrReleasedDate() {
		String strDate = "";
		try {
			strDate = DateUtils.dateToString(this.releasedDate, DateUtils.Formats.STR_DATE_TIME_FORMAT_YYYYMMDD);
		} catch (Exception e) {
		}
		return strDate;
	}

	/**
	 * @return the locale
	 */
	public String getLocale() {
		return locale;
	}

	/**
	 * @param locale
	 *            the locale to set
	 */
	public void setLocale(String locale) {
		this.locale = locale;
	}

	/**
	 * Get type of file research
	 * 
	 * @return -2: not attach file 1: attach doc file 2: attach pdf file -1:
	 *         remain : attach file not document and pdf type
	 */
	public int getDocType() {
		if (this.fileName == null || this.fileName.trim().length() == 0) {
			return -2;
		} else if (this.fileName.toUpperCase().endsWith(".DOC")) {
			return 1;
		} else if (this.fileName.toUpperCase().endsWith(".PDF")) {
			return 2;
		} else if (this.fileName.toUpperCase().endsWith(".XLS")) {
			return 3;
		} else if (this.fileName.toUpperCase().endsWith(".ZIP") || this.fileName.toUpperCase().endsWith(".RAR")) {
			return 4;
		} else {
			return -1;
		}
	}

	/**
	 * 
	 * @return
	 */
	public String getDisplayReleaseDate() {
		String strDate = "";
		try {
			strDate = DateUtils.dateToString(this.releasedDate, "dd-MMM-yyyy");
		} catch (Exception e) {
		}
		return strDate;
	}

	public String getDisplayReleaseDateStr() {
		String strDate = "";
		try {
			strDate = DateUtils.dateToString(this.releasedDate, "dd/MM/yy");
		} catch (Exception e) {
		}
		return strDate;
	}

	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}
}