package vn.com.vndirect.domain;

import com.google.code.ssm.api.CacheKeyMethod;

/**
 * CmsDataRef generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoDataRef extends BaseBean implements java.io.Serializable {

	// Fields

	private Long dataRefId;
	private String groupCode;
	private String itemCode;
	private String description;
	private String locale;
	private String orderby;

	// Constructors

	/** default constructor */
	public IfoDataRef() {
	}

	/** full constructor */
	public IfoDataRef(Long dataRefId, String groupCode, String itemCode, String description, String locale) {
		this.dataRefId = dataRefId;
		this.groupCode = groupCode;
		this.itemCode = itemCode;
		this.description = description;
		this.locale = locale;
	}

	// Property accessors

	public Long getDataRefId() {
		return this.dataRefId;
	}

	public void setDataRefId(Long dataRefId) {
		this.dataRefId = dataRefId;
	}

	public String getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public String toString() {
		StringBuffer buf = new StringBuffer();
		buf.append("IfoDataRef@").append(this.hashCode()).append("[");
		buf.append("groupCode=" + groupCode);
		buf.append(",itemCode=" + itemCode);
		buf.append(",description=" + description);
		buf.append(",locale=" + locale);
		buf.append("]");
		return buf.toString();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((this.dataRefId == null) ? 0 : this.dataRefId.hashCode());
		result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
		result = prime * result + ((this.groupCode == null) ? 0 : this.groupCode.hashCode());
		result = prime * result + ((this.itemCode == null) ? 0 : this.itemCode.hashCode());
		result = prime * result + ((this.locale == null) ? 0 : this.locale.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (!(obj instanceof IfoDataRef))
			return false;
		final IfoDataRef other = (IfoDataRef) obj;
		if (this.dataRefId == null) {
			if (other.dataRefId != null)
				return false;
		} else if (!this.dataRefId.equals(other.dataRefId))
			return false;
		if (this.description == null) {
			if (other.description != null)
				return false;
		} else if (!this.description.equals(other.description))
			return false;
		if (this.groupCode == null) {
			if (other.groupCode != null)
				return false;
		} else if (!this.groupCode.equals(other.groupCode))
			return false;
		if (this.itemCode == null) {
			if (other.itemCode != null)
				return false;
		} else if (!this.itemCode.equals(other.itemCode))
			return false;
		if (this.locale == null) {
			if (other.locale != null)
				return false;
		} else if (!this.locale.equals(other.locale))
			return false;
		return true;
	}

	public void setOrderby(String orderby) {
		this.orderby = orderby;
	}

	public String getOrderby() {
		return orderby;
	}
	
	@CacheKeyMethod
	public String createCacheKey(){
		return groupCode.hashCode() + "@" + locale;
	}
}