package vn.com.vndirect.domain;

import java.util.Date;

/**
 * IfoExchangeCode generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoExchangeCode extends BaseBean implements java.io.Serializable {

	// Fields

	private String exchangeCode;
	private String exchangeName;
	private String countryCode;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;

	// Constructors

	/** default constructor */
	public IfoExchangeCode() {
	}

	/** minimal constructor */
	public IfoExchangeCode(String exchangeCode) {
		this.exchangeCode = exchangeCode;
	}

	/** full constructor */
	public IfoExchangeCode(String exchangeCode, String exchangeName, String countryCode, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
		this.exchangeCode = exchangeCode;
		this.exchangeName = exchangeName;
		this.countryCode = countryCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	// Property accessors

	public String getExchangeCode() {
		return this.exchangeCode;
	}

	public void setExchangeCode(String exchangeCode) {
		this.exchangeCode = exchangeCode;
	}

	public String getExchangeName() {
		return this.exchangeName;
	}

	public void setExchangeName(String exchangeName) {
		this.exchangeName = exchangeName;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}