package vn.com.vndirect.domain;

/**
 * IfoFinancialHighlightView generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoFinancialHighlightView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoFinancialHighlightViewId id;

	// Constructors

	/** default constructor */
	public IfoFinancialHighlightView() {
	}

	// Property accessors

	public IfoFinancialHighlightViewId getId() {
		return this.id;
	}

	public void setId(IfoFinancialHighlightViewId id) {
		this.id = id;
	}

}