package vn.com.vndirect.domain;

/**
 * IfoIncomeView generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoIncomeView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoIncomeViewId id;

	// Constructors

	/** default constructor */
	public IfoIncomeView() {
	}

	// Property accessors

	public IfoIncomeViewId getId() {
		return this.id;
	}

	public void setId(IfoIncomeViewId id) {
		this.id = id;
	}

}