package vn.com.vndirect.domain;

/**
 * IfoInvestorRightsView generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoInvestorRightsView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoInvestorRightsViewId id;

	// Constructors

	/** default constructor */
	public IfoInvestorRightsView() {
	}

	// Property accessors

	public IfoInvestorRightsViewId getId() {
		return this.id;
	}

	public void setId(IfoInvestorRightsViewId id) {
		this.id = id;
	}

}