package vn.com.vndirect.domain;

import java.util.Date;

import vn.com.vndirect.commons.utility.VNDirectDateUtils;

/**
 * IfoInvestorRightsViewId generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoInvestorRightsViewId extends BaseBean implements java.io.Serializable {

	// Fields

	private Long companyId;
	private String secCode;
	private String sharesActionDesc;
	private Double ratio;
	private Date xdate;
	private String locale;

	// Constructors

	/** default constructor */
	public IfoInvestorRightsViewId() {
	}

	/** full constructor */
	public IfoInvestorRightsViewId(Long companyId, String type, Double ratio, Date xDate, String locale) {
		this.companyId = companyId;
		this.secCode = type;
		this.ratio = ratio;
		this.xdate = xDate;
		this.locale = locale;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	/**
	 * @return the ratio
	 */
	public Double getRatio() {
		return ratio;
	}

	/**
	 * @param ratio
	 *            the ratio to set
	 */
	public void setRatio(Double ratio) {
		this.ratio = ratio;
	}

	/**
	 * @return the type
	 */
	public String getSecCode() {
		return secCode;
	}

	/**
	 * @param type
	 *            the type to set
	 */
	public void setSecCode(String type) {
		this.secCode = type;
	}

	/**
	 * @return the xDate
	 */
	public Date getXdate() {
		return xdate;
	}

	/**
	 * @param date
	 *            the xDate to set
	 */
	public void setXdate(Date date) {
		xdate = date;
	}

	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	/**
	 * @return the strXdate
	 */
	public String getXDateStr() {

		String strDate = "";
		try {
			strDate = VNDirectDateUtils.dateToString(this.xdate, VNDirectDateUtils.Formats.STR_DATE_TIME_FORMAT_YYYYMMDD);
		} catch (Exception e) {
		}
		return strDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoInvestorRightsViewId))
			return false;
		IfoInvestorRightsViewId castOther = (IfoInvestorRightsViewId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getLocale() == castOther.getLocale()) || (this.getLocale() != null && castOther.getLocale() != null && this.getLocale().equals(castOther.getLocale())))
				&& ((this.getRatio() == castOther.getRatio()) || (this.getRatio() != null && castOther.getRatio() != null && this.getRatio().equals(castOther.getRatio())))
				&& ((this.getSecCode() == castOther.getSecCode()) || (this.getSecCode() != null && castOther.getSecCode() != null && this.getSecCode().equals(castOther.getSecCode())))
				&& ((this.getXdate() == castOther.getXdate()) || (this.getXdate() != null && castOther.getXdate() != null && this.getXdate().equals(castOther.getXdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getLocale() == null ? 0 : this.getLocale().hashCode());
		result = 37 * result + (getRatio() == null ? 0 : this.getRatio().hashCode());
		result = 37 * result + (getSecCode() == null ? 0 : this.getSecCode().hashCode());
		result = 37 * result + (getXdate() == null ? 0 : this.getXdate().hashCode());

		return result;
	}

	/**
	 * @return the sharesActionDesc
	 */
	public String getSharesActionDesc() {
		return sharesActionDesc;
	}

	/**
	 * @param sharesActionDesc
	 *            the sharesActionDesc to set
	 */
	public void setSharesActionDesc(String sharesActionDesc) {
		this.sharesActionDesc = sharesActionDesc;
	}

}