package vn.com.vndirect.domain;

import java.util.Date;

import vn.com.web.commons.utility.DateUtils;

/**
 * IfoInsiderTransactionViewId generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoInsiderTransactionViewId extends BaseBean implements java.io.Serializable {

	// Fields
	private Long companyId;
	private String insider;
	private String position;
	private Double sharesHeld;
	private String transaction;
	private Double price;
	private Date transactionDate;
	private String locale;

	// Constructors

	/** default constructor */
	public IfoInsiderTransactionViewId() {
	}

	/** full constructor */
	public IfoInsiderTransactionViewId(Long companyId, String insider, String position, Double sharesHeld, String transaction, Double price, Date transactionDate) {
		this.companyId = companyId;
		this.insider = insider;
		this.position = position;
		this.sharesHeld = sharesHeld;
		this.transaction = transaction;
		this.price = price;
		this.transactionDate = transactionDate;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getInsider() {
		return this.insider;
	}

	public void setInsider(String insider) {
		this.insider = insider;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Double getSharesHeld() {
		return this.sharesHeld;
	}

	public void setSharesHeld(Double sharesHeld) {
		this.sharesHeld = sharesHeld;
	}

	public String getTransaction() {
		return this.transaction;
	}

	public void setTransaction(String transaction) {
		this.transaction = transaction;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	/**
	 * @return the transactionDateStr
	 */
	public String getTransactionDateStr() {

		String strDate = "";
		try {
			strDate = DateUtils.dateToString(this.transactionDate, DateUtils.Formats.STR_DATE_TIME_FORMAT_YYYYMMDD);
		} catch (Exception e) {
		}
		return strDate;

	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoInsiderTransactionViewId))
			return false;
		IfoInsiderTransactionViewId castOther = (IfoInsiderTransactionViewId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getInsider() == castOther.getInsider()) || (this.getInsider() != null && castOther.getInsider() != null && this.getInsider().equals(castOther.getInsider())))
				&& ((this.getPosition() == castOther.getPosition()) || (this.getPosition() != null && castOther.getPosition() != null && this.getPosition().equals(castOther.getPosition())))
				&& ((this.getSharesHeld() == castOther.getSharesHeld()) || (this.getSharesHeld() != null && castOther.getSharesHeld() != null && this.getSharesHeld().equals(castOther.getSharesHeld())))
				&& ((this.getTransaction() == castOther.getTransaction()) || (this.getTransaction() != null && castOther.getTransaction() != null && this.getTransaction().equals(
						castOther.getTransaction())))
				&& ((this.getPrice() == castOther.getPrice()) || (this.getPrice() != null && castOther.getPrice() != null && this.getPrice().equals(castOther.getPrice())))
				&& ((this.getTransactionDate() == castOther.getTransactionDate()) || (this.getTransactionDate() != null && castOther.getTransactionDate() != null && this.getTransactionDate().equals(
						castOther.getTransactionDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getInsider() == null ? 0 : this.getInsider().hashCode());
		result = 37 * result + (getPosition() == null ? 0 : this.getPosition().hashCode());
		result = 37 * result + (getSharesHeld() == null ? 0 : this.getSharesHeld().hashCode());
		result = 37 * result + (getTransaction() == null ? 0 : this.getTransaction().hashCode());
		result = 37 * result + (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37 * result + (getTransactionDate() == null ? 0 : this.getTransactionDate().hashCode());
		return result;
	}

}