package vn.com.vndirect.domain;

/**
 * IfoInsiderTransactionView generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoInsiderTransactionView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoInsiderTransactionViewId id;

	// Constructors

	/** default constructor */
	public IfoInsiderTransactionView() {
	}

	// Property accessors

	public IfoInsiderTransactionViewId getId() {
		return this.id;
	}

	public void setId(IfoInsiderTransactionViewId id) {
		this.id = id;
	}

}