package vn.com.vndirect.domain;

import java.util.Date;

/**
 * IfoKeyRatioViewId generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoKeyRatioViewId extends BaseBean implements java.io.Serializable {

	// Fields

	private Long companyId;
	private Long dataHeaderId;
	private String reportType;
	private Date fiscalDate;
	private Date reportDate;
	private String currencyCode;
	private String itemCode;
	private String itemName;
	private Double numericValue;
	private String textValue;
	private Long displayOrder;
	private Long displayLevel;
	private String locale;

	// Constructors

	/** default constructor */
	public IfoKeyRatioViewId() {
	}

	/** full constructor */
	public IfoKeyRatioViewId(Long companyId, Long dataHeaderId, String reportType, Date fiscalDate, Date reportDate, String currencyCode, String itemCode, String itemName, Double nubericValue,
			String textValue, Long displayOrder, Long displayLevel, String locale) {
		this.companyId = companyId;
		this.dataHeaderId = dataHeaderId;
		this.reportType = reportType;
		this.fiscalDate = fiscalDate;
		this.reportDate = reportDate;
		this.currencyCode = currencyCode;
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.numericValue = nubericValue;
		this.textValue = textValue;
		this.displayOrder = displayOrder;
		this.displayLevel = displayLevel;
		this.locale = locale;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public Long getDataHeaderId() {
		return this.dataHeaderId;
	}

	public void setDataHeaderId(Long dataHeaderId) {
		this.dataHeaderId = dataHeaderId;
	}

	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public Date getFiscalDate() {
		return this.fiscalDate;
	}

	public void setFiscalDate(Date fiscalDate) {
		this.fiscalDate = fiscalDate;
	}

	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getTextValue() {
		return this.textValue;
	}

	public void setTextValue(String textValue) {
		this.textValue = textValue;
	}

	public Long getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Long displayOrder) {
		this.displayOrder = displayOrder;
	}

	public Long getDisplayLevel() {
		return this.displayLevel;
	}

	public void setDisplayLevel(Long displayLevel) {
		this.displayLevel = displayLevel;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public Double getNumericValue() {
		return numericValue;
	}

	public void setNumericValue(Double nubericValue) {
		this.numericValue = nubericValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoKeyRatioViewId))
			return false;
		IfoKeyRatioViewId castOther = (IfoKeyRatioViewId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getDataHeaderId() == castOther.getDataHeaderId()) || (this.getDataHeaderId() != null && castOther.getDataHeaderId() != null && this.getDataHeaderId().equals(
						castOther.getDataHeaderId())))
				&& ((this.getReportType() == castOther.getReportType()) || (this.getReportType() != null && castOther.getReportType() != null && this.getReportType().equals(castOther.getReportType())))
				&& ((this.getFiscalDate() == castOther.getFiscalDate()) || (this.getFiscalDate() != null && castOther.getFiscalDate() != null && this.getFiscalDate().equals(castOther.getFiscalDate())))
				&& ((this.getReportDate() == castOther.getReportDate()) || (this.getReportDate() != null && castOther.getReportDate() != null && this.getReportDate().equals(castOther.getReportDate())))
				&& ((this.getCurrencyCode() == castOther.getCurrencyCode()) || (this.getCurrencyCode() != null && castOther.getCurrencyCode() != null && this.getCurrencyCode().equals(
						castOther.getCurrencyCode())))
				&& ((this.getItemCode() == castOther.getItemCode()) || (this.getItemCode() != null && castOther.getItemCode() != null && this.getItemCode().equals(castOther.getItemCode())))
				&& ((this.getItemName() == castOther.getItemName()) || (this.getItemName() != null && castOther.getItemName() != null && this.getItemName().equals(castOther.getItemName())))
				&& ((this.getNumericValue() == castOther.getNumericValue()) || (this.getNumericValue() != null && castOther.getNumericValue() != null && this.getNumericValue().equals(
						castOther.getNumericValue())))
				&& ((this.getTextValue() == castOther.getTextValue()) || (this.getTextValue() != null && castOther.getTextValue() != null && this.getTextValue().equals(castOther.getTextValue())))
				&& ((this.getDisplayOrder() == castOther.getDisplayOrder()) || (this.getDisplayOrder() != null && castOther.getDisplayOrder() != null && this.getDisplayOrder().equals(
						castOther.getDisplayOrder())))
				&& ((this.getDisplayLevel() == castOther.getDisplayLevel()) || (this.getDisplayLevel() != null && castOther.getDisplayLevel() != null && this.getDisplayLevel().equals(
						castOther.getDisplayLevel())))
				&& ((this.getLocale() == castOther.getLocale()) || (this.getLocale() != null && castOther.getLocale() != null && this.getLocale().equals(castOther.getLocale())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getDataHeaderId() == null ? 0 : this.getDataHeaderId().hashCode());
		result = 37 * result + (getReportType() == null ? 0 : this.getReportType().hashCode());
		result = 37 * result + (getFiscalDate() == null ? 0 : this.getFiscalDate().hashCode());
		result = 37 * result + (getReportDate() == null ? 0 : this.getReportDate().hashCode());
		result = 37 * result + (getCurrencyCode() == null ? 0 : this.getCurrencyCode().hashCode());
		result = 37 * result + (getItemCode() == null ? 0 : this.getItemCode().hashCode());
		result = 37 * result + (getItemName() == null ? 0 : this.getItemName().hashCode());
		result = 37 * result + (getNumericValue() == null ? 0 : this.getNumericValue().hashCode());
		result = 37 * result + (getTextValue() == null ? 0 : this.getTextValue().hashCode());
		result = 37 * result + (getDisplayOrder() == null ? 0 : this.getDisplayOrder().hashCode());
		result = 37 * result + (getDisplayLevel() == null ? 0 : this.getDisplayLevel().hashCode());
		result = 37 * result + (getLocale() == null ? 0 : this.getLocale().hashCode());
		return result;
	}

}