package vn.com.vndirect.domain;

/**
 * IfoKeyRatioView generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoKeyRatioView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoKeyRatioViewId id;

	// Constructors

	/** default constructor */
	public IfoKeyRatioView() {
	}

	// Property accessors

	public IfoKeyRatioViewId getId() {
		return this.id;
	}

	public void setId(IfoKeyRatioViewId id) {
		this.id = id;
	}

}