package vn.com.vndirect.domain;

import java.util.Date;

import vn.com.web.commons.utility.DateUtils;

/**
 * IfoMaijorHolderViewId generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoMaijorHolderViewId extends BaseBean implements java.io.Serializable {
	private Long companyId;
	private String holders;
	private String position;
	private Double shares;
	private Date reported;
	private Double ownerRatio;
	private String locale;

	// Constructors

	/** default constructor */
	public IfoMaijorHolderViewId() {
	}

	/** full constructor */
	public IfoMaijorHolderViewId(Long companyId, String holders, String position, Double shares, Date reported) {
		this.companyId = companyId;
		this.holders = holders;
		this.position = position;
		this.shares = shares;
		this.reported = reported;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getHolders() {
		return this.holders;
	}

	public void setHolders(String holders) {
		this.holders = holders;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Double getShares() {
		return this.shares;
	}

	public void setShares(Double shares) {
		this.shares = shares;
	}

	public Date getReported() {
		return this.reported;
	}

	public void setReported(Date reported) {
		this.reported = reported;
	}

	/**
	 * @return the reportedStr
	 */
	public String getReportedStr() {

		String strDate = "";
		try {
			strDate = DateUtils.dateToString(this.reported, DateUtils.Formats.STR_DATE_TIME_FORMAT_DDMMYYYY);
		} catch (Exception e) {
		}
		return strDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoMaijorHolderViewId))
			return false;
		IfoMaijorHolderViewId castOther = (IfoMaijorHolderViewId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getHolders() == castOther.getHolders()) || (this.getHolders() != null && castOther.getHolders() != null && this.getHolders().equals(castOther.getHolders())))
				&& ((this.getPosition() == castOther.getPosition()) || (this.getPosition() != null && castOther.getPosition() != null && this.getPosition().equals(castOther.getPosition())))
				&& ((this.getShares() == castOther.getShares()) || (this.getShares() != null && castOther.getShares() != null && this.getShares().equals(castOther.getShares())))
				&& ((this.getReported() == castOther.getReported()) || (this.getReported() != null && castOther.getReported() != null && this.getReported().equals(castOther.getReported())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getHolders() == null ? 0 : this.getHolders().hashCode());
		result = 37 * result + (getPosition() == null ? 0 : this.getPosition().hashCode());
		result = 37 * result + (getShares() == null ? 0 : this.getShares().hashCode());
		result = 37 * result + (getReported() == null ? 0 : this.getReported().hashCode());
		return result;
	}

	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public Double getOwnerRatio() {
		return ownerRatio;
	}

	public void setOwnerRatio(Double ownerRatio) {
		this.ownerRatio = ownerRatio;
	}

}