package vn.com.vndirect.domain;

/**
 * IfoMaijorHolderView generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class IfoMaijorHolderView extends BaseBean implements java.io.Serializable {
	// Fields
	private IfoMaijorHolderViewId id;

	// Constructors
	/** default constructor */
	public IfoMaijorHolderView() {
	}

	// Property accessors
	public IfoMaijorHolderViewId getId() {
		return this.id;
	}

	public void setId(IfoMaijorHolderViewId id) {
		this.id = id;
	}

}