package vn.com.vndirect.domain;

/**
 * IfoSectorCode generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoSectorCode implements java.io.Serializable {

	// Fields

	private IfoSectorCodeId id;

	// Constructors

	/** default constructor */
	public IfoSectorCode() {
	}

	// Property accessors

	public IfoSectorCodeId getId() {
		return this.id;
	}

	public void setId(IfoSectorCodeId id) {
		this.id = id;
	}

}