package vn.com.vndirect.domain;

/**
 * IfoSecPriceView generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoSecPriceView extends BaseBean implements java.io.Serializable {

	private double chgIndex;
	private double pctIndex;

	private IfoSecPriceViewId id;

	/** default constructor */
	public IfoSecPriceView() {
	}

	// Property accessors

	public IfoSecPriceViewId getId() {
		return this.id;
	}

	public void setId(IfoSecPriceViewId id) {
		this.id = id;
	}

	/**
	 * @return the chgIndex
	 */
	public double getChgIndex() {
		return this.chgIndex;
	}

	/**
	 * @param chgIndex
	 *            the chgIndex to set
	 */
	public void setChgIndex(double chgIndex) {
		this.chgIndex = chgIndex;
	}

	/**
	 * @return the pctIndex
	 */
	public double getPctIndex() {
		return this.pctIndex;
	}

	/**
	 * @param pctIndex
	 *            the pctIndex to set
	 */
	public void setPctIndex(double pctIndex) {
		this.pctIndex = pctIndex;
	}
}