package vn.com.vndirect.domain;

/**
 * IfoSecIndexView generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoSecIndexView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoSecIndexViewId id;

	// Constructors

	/** default constructor */
	public IfoSecIndexView() {
	}

	// Property accessors

	public IfoSecIndexViewId getId() {
		return this.id;
	}

	public void setId(IfoSecIndexViewId id) {
		this.id = id;
	}

}