package vn.com.vndirect.domain;

import java.util.Date;

/**
 * IfoSectorCodeId generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoSectorCodeId implements java.io.Serializable {

	// Fields

	private String sectorCode;
	private String sectorName;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private String locale;

	// Constructors

	/** default constructor */
	public IfoSectorCodeId() {
	}

	/** full constructor */
	public IfoSectorCodeId(String sectorCode, String sectorName, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy, String locale) {
		this.sectorCode = sectorCode;
		this.sectorName = sectorName;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.locale = locale;
	}

	// Property accessors

	public String getSectorCode() {
		return this.sectorCode;
	}

	public void setSectorCode(String sectorCode) {
		this.sectorCode = sectorCode;
	}

	public String getSectorName() {
		return this.sectorName;
	}

	public void setSectorName(String sectorName) {
		this.sectorName = sectorName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoSectorCodeId))
			return false;
		IfoSectorCodeId castOther = (IfoSectorCodeId) other;

		return ((this.getSectorCode() == castOther.getSectorCode()) || (this.getSectorCode() != null && castOther.getSectorCode() != null && this.getSectorCode().equals(castOther.getSectorCode())))
				&& ((this.getSectorName() == castOther.getSectorName()) || (this.getSectorName() != null && castOther.getSectorName() != null && this.getSectorName().equals(castOther.getSectorName())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate()) || (this.getCreatedDate() != null && castOther.getCreatedDate() != null && this.getCreatedDate().equals(
						castOther.getCreatedDate())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getModifiedDate() == castOther.getModifiedDate()) || (this.getModifiedDate() != null && castOther.getModifiedDate() != null && this.getModifiedDate().equals(
						castOther.getModifiedDate())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this.getModifiedBy() != null && castOther.getModifiedBy() != null && this.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getLocale() == castOther.getLocale()) || (this.getLocale() != null && castOther.getLocale() != null && this.getLocale().equals(castOther.getLocale())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSectorCode() == null ? 0 : this.getSectorCode().hashCode());
		result = 37 * result + (getSectorName() == null ? 0 : this.getSectorName().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getModifiedDate() == null ? 0 : this.getModifiedDate().hashCode());
		result = 37 * result + (getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode());
		result = 37 * result + (getLocale() == null ? 0 : this.getLocale().hashCode());
		return result;
	}

}