package vn.com.vndirect.domain;

/**
 * IfoValuationMeasuresViewId generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoValuationMeasuresViewId extends BaseBean implements java.io.Serializable {

	// Fields

	private Long companyId;
	private Long itemCode;
	private String itemName;
	private Double numericValue;
	private String textValue;
	private Long displayOrder;
	private Long displayLevel;
	private String locale;

	// Constructors

	/** default constructor */
	public IfoValuationMeasuresViewId() {
	}

	/** full constructor */
	public IfoValuationMeasuresViewId(Long companyId, Long itemCode, String itemName, Double numericValue, String textValue, Long displayOrder, Long displayLevel, String locale) {
		this.companyId = companyId;
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.textValue = textValue;
		this.displayOrder = displayOrder;
		this.displayLevel = displayLevel;
		this.locale = locale;
	}

	// Property accessors

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	/**
	 * @return the displayLevel
	 */
	public Long getDisplayLevel() {
		return displayLevel;
	}

	/**
	 * @param displayLevel
	 *            the displayLevel to set
	 */
	public void setDisplayLevel(Long displayLevel) {
		this.displayLevel = displayLevel;
	}

	/**
	 * @return the displayOrder
	 */
	public Long getDisplayOrder() {
		return displayOrder;
	}

	/**
	 * @param displayOrder
	 *            the displayOrder to set
	 */
	public void setDisplayOrder(Long displayOrder) {
		this.displayOrder = displayOrder;
	}

	/**
	 * @return the itemCode
	 */
	public Long getItemCode() {
		return itemCode;
	}

	/**
	 * @param itemCode
	 *            the itemCode to set
	 */
	public void setItemCode(Long itemCode) {
		this.itemCode = itemCode;
	}

	/**
	 * @return the itemName
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * @param itemName
	 *            the itemName to set
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/**
	 * @return the locale
	 */
	public String getLocale() {
		return locale;
	}

	/**
	 * @param locale
	 *            the locale to set
	 */
	public void setLocale(String locale) {
		this.locale = locale;
	}

	/**
	 * @return the numericValue
	 */
	public Double getNumericValue() {
		return numericValue;
	}

	/**
	 * @param numericValue
	 *            the numericValue to set
	 */
	public void setNumericValue(Double numericValue) {
		this.numericValue = numericValue;
	}

	/**
	 * @return the textValue
	 */
	public String getTextValue() {
		return textValue;
	}

	/**
	 * @param textValue
	 *            the textValue to set
	 */
	public void setTextValue(String textValue) {
		this.textValue = textValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfoValuationMeasuresViewId))
			return false;
		IfoValuationMeasuresViewId castOther = (IfoValuationMeasuresViewId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null && castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getDisplayLevel() == castOther.getDisplayLevel()) || (this.getDisplayLevel() != null && castOther.getDisplayLevel() != null && this.getDisplayLevel().equals(
						castOther.getDisplayLevel())))
				&& ((this.getDisplayOrder() == castOther.getDisplayOrder()) || (this.getDisplayOrder() != null && castOther.getDisplayOrder() != null && this.getDisplayOrder().equals(
						castOther.getDisplayOrder())))
				&& ((this.getItemCode() == castOther.getItemCode()) || (this.getItemCode() != null && castOther.getItemCode() != null && this.getItemCode().equals(castOther.getItemCode())))
				&& ((this.getItemName() == castOther.getItemName()) || (this.getItemName() != null && castOther.getItemName() != null && this.getItemName().equals(castOther.getItemName())))
				&& ((this.getLocale() == castOther.getLocale()) || (this.getLocale() != null && castOther.getLocale() != null && this.getLocale().equals(castOther.getLocale())))
				&& ((this.getNumericValue() == castOther.getNumericValue()) || (this.getNumericValue() != null && castOther.getNumericValue() != null && this.getNumericValue().equals(
						castOther.getNumericValue())))
				&& ((this.getTextValue() == castOther.getTextValue()) || (this.getTextValue() != null && castOther.getTextValue() != null && this.getTextValue().equals(castOther.getTextValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getDisplayLevel() == null ? 0 : this.getDisplayLevel().hashCode());
		result = 37 * result + (getDisplayOrder() == null ? 0 : this.getDisplayOrder().hashCode());
		result = 37 * result + (getItemCode() == null ? 0 : this.getItemCode().hashCode());
		result = 37 * result + (getItemName() == null ? 0 : this.getItemName().hashCode());
		result = 37 * result + (getLocale() == null ? 0 : this.getLocale().hashCode());
		result = 37 * result + (getNumericValue() == null ? 0 : this.getNumericValue().hashCode());
		result = 37 * result + (getTextValue() == null ? 0 : this.getTextValue().hashCode());

		return result;
	}

}