package vn.com.vndirect.domain;

/**
 * IfoValuationMeasuresView generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class IfoValuationMeasuresView extends BaseBean implements java.io.Serializable {

	// Fields

	private IfoValuationMeasuresViewId id;

	// Constructors

	/** default constructor */
	public IfoValuationMeasuresView() {
	}

	// Property accessors

	public IfoValuationMeasuresViewId getId() {
		return this.id;
	}

	public void setId(IfoValuationMeasuresViewId id) {
		this.id = id;
	}

}