package vn.com.vndirect.domain;

import java.util.Date;

/**
 * IfoSectorCodeId generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class MatchOrderId implements java.io.Serializable {

	// Fields

	private String floorCode;
	private String code;
	private Date tradingDate;
	private String time;
	private Double matchPrice;
	private Double matchQuantity;

	// Constructors

	/** default constructor */
	public MatchOrderId() {
	}

	/** full constructor */
	public MatchOrderId(String floorCode, String code, Date tradingDate, String time, Double matchPrice, Double matchQuantity) {
		this.floorCode = floorCode;
		this.code = code;
		this.tradingDate = tradingDate;
		this.time = time;
		this.matchPrice = matchPrice;
		this.matchQuantity = matchQuantity;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getFloorCode() {
		return floorCode;
	}

	public void setFloorCode(String floorCode) {
		this.floorCode = floorCode;
	}

	public Double getMatchPrice() {
		return matchPrice;
	}

	public void setMatchPrice(Double matchPrice) {
		this.matchPrice = matchPrice;
	}

	public Double getMatchQuantity() {
		return matchQuantity;
	}

	public void setMatchQuantity(Double matchQuantity) {
		this.matchQuantity = matchQuantity;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Date getTradingDate() {
		return tradingDate;
	}

	public void setTradingDate(Date tradingDate) {
		this.tradingDate = tradingDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatchOrderId))
			return false;
		MatchOrderId castOther = (MatchOrderId) other;

		return ((this.getFloorCode() == castOther.getFloorCode()) || (this.getFloorCode() != null && castOther.getFloorCode() != null && this.getFloorCode().equals(castOther.getFloorCode())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null && this.getCode().equals(castOther.getCode())))
				&& ((this.getTradingDate() == castOther.getTradingDate()) || (this.getTradingDate() != null && castOther.getTradingDate() != null && this.getTradingDate().equals(
						castOther.getTradingDate())))
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null && this.getTime().equals(castOther.getTime())))
				&& ((this.getMatchPrice() == castOther.getMatchPrice()) || (this.getMatchPrice() != null && castOther.getMatchPrice() != null && this.getMatchPrice().equals(castOther.getMatchPrice())))
				&& ((this.getMatchQuantity() == castOther.getMatchQuantity()) || (this.getMatchQuantity() != null && castOther.getMatchQuantity() != null && this.getMatchQuantity().equals(
						castOther.getMatchQuantity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFloorCode() == null ? 0 : this.getFloorCode().hashCode());
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (getTradingDate() == null ? 0 : this.getTradingDate().hashCode());
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		result = 37 * result + (getMatchPrice() == null ? 0 : this.getMatchPrice().hashCode());
		result = 37 * result + (getMatchQuantity() == null ? 0 : this.getMatchQuantity().hashCode());

		return result;
	}

}