package vn.com.vndirect.domain;

/**
 * IfoSectorCode generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class MatchOrder implements java.io.Serializable {

	// Fields

	private MatchOrderId id;

	// Constructors

	/** default constructor */
	public MatchOrder() {
	}

	public MatchOrderId getId() {
		return id;
	}

	public void setId(MatchOrderId id) {
		this.id = id;
	}

}