package vn.com.vndirect.domain;

import java.util.Calendar;
import java.util.Date;

import vn.com.vndirect.commons.utility.Constants;
import vn.com.web.commons.servercfg.ServerConfig;

/**
 * OnlineUser generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class OnlineUser extends BaseBean implements java.io.Serializable {

	// Fields
	private String activeKey;
	private String activeStatus;

	private Long onlineUserId;

	private String fullName;	

	private String userName;

	private String password;

	private String idgId;

	private String customerId;

	private Date createdDate;

	private String createdBy;

	private Date dob;

	private String address;

	private String email;

	private String status;

	private ServiceInfo[] serviceInfo;

	// Constructors

	private String sex;

	private String strDob;

	private String province;

	private String country;

	private String telephone;

	private String newPassword;

	public String getActiveStatus() {
		return activeStatus;
	}

	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	/** default constructor */
	public OnlineUser() {
	}

	/** full constructor */
	public OnlineUser(String fullName, String userName, String password, String idgId, String customerId, Date createdDate, String createdBy, Date dob, String address, String email, String status) {
		this.fullName = fullName;
		this.userName = userName;
		this.password = password;
		this.idgId = idgId;
		this.customerId = customerId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.dob = dob;
		this.address = address;
		this.email = email;
		this.status = status;
	}

	// Property accessors

	public Long getOnlineUserId() {
		return this.onlineUserId;
	}

	public void setOnlineUserId(Long onlineUserId) {
		this.onlineUserId = onlineUserId;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getIdgId() {
		return this.idgId;
	}

	public void setIdgId(String idgId) {
		this.idgId = idgId;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean isActive() {
		return this.status != null && this.status.equals(ServerConfig.getOnlineValue(Constants.IServerConfig.DataRef.ItemCodes.OnlineUserStatus.ONLINE_ACTIVE));
	}

	public boolean isDisabled() {
		return this.status != null && this.status.equals(ServerConfig.getOnlineValue(Constants.IServerConfig.DataRef.ItemCodes.OnlineUserStatus.ONLINE_DISABLED));
	}

	public vn.com.vndirect.wsclient.onlineuser.OnlineUser getOnlineUser() {
		vn.com.vndirect.wsclient.onlineuser.OnlineUser userOnline = new vn.com.vndirect.wsclient.onlineuser.OnlineUser();
		userOnline.setFullName(fullName);
		userOnline.setUserName(userName);
		userOnline.setPassword(password);
		userOnline.setIdgId(idgId);
		userOnline.setCustomerId(customerId);
		Calendar calendar = Calendar.getInstance();
		if (this.createdDate != null) {
			calendar.setTime(this.createdDate);
			userOnline.setCreatedDate(calendar);
		}

		calendar = Calendar.getInstance();
		if (this.dob != null) {
			calendar.setTime(this.dob);
			userOnline.setDob(calendar);
		}
		userOnline.setEmail(email);
		userOnline.setStatus(status);
		userOnline.setAddress(address);
		userOnline.setSex(sex);
		userOnline.setCountry(country);
		userOnline.setProvince(province);
		userOnline.setTelephone(telephone);
		return userOnline;
	}

	public vn.com.vndirect.wsclient.onlineuser.ActiveOnlineUser getActiveOnlineUser() {

		vn.com.vndirect.wsclient.onlineuser.ActiveOnlineUser activeOnlineUser = new vn.com.vndirect.wsclient.onlineuser.ActiveOnlineUser();

		activeOnlineUser.setUserName(userName);
		activeOnlineUser.setPassword(password);
		activeOnlineUser.setActiveKey(activeKey);
		return activeOnlineUser;
	}

	public String getActiveKey() {
		return activeKey;
	}

	public void setActiveKey(String activeKey) {
		this.activeKey = activeKey;
	}

	public ServiceInfo[] getServiceInfo() {
		return serviceInfo;
	}

	public void setServiceInfo(ServiceInfo[] serviceInfo) {
		this.serviceInfo = serviceInfo;
	}

	public String toString() {
		StringBuffer strBuf = new StringBuffer();
		if (this.serviceInfo != null) {
			int i, size = serviceInfo.length;
			for (i = 0; i < size; i++) {
				strBuf.append(serviceInfo[i]).append(",");
			}
		}
		return "OnlineUser-[userName:" + userName + ", idgId:" + idgId + ", customerId:" + customerId + ", ServiceInfos: " + strBuf + "]";
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getStrDob() {
		return strDob;
	}

	public void setStrDob(String strDob) {
		this.strDob = strDob;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getNewPassword() {
		return newPassword;
	}

	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}
}