package vn.com.vndirect.domain;

import java.util.Date;

/**
 * SecInfo generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class SecInfo extends BaseBean implements java.io.Serializable {

	// Fields

	@Override
	public boolean equals(Object obj) {
		// TODO Auto-generated method stub
		return this.symbol.equalsIgnoreCase(((SecInfo) obj).getSymbol());
	}

	private String floorCode;
	private double dateNo;
	private Date tradingDate;
	private String time;
	private double stockId;
	private String code;
	private double stockType;
	private double totalListingQtty;
	private double tradingUnit;
	private double listtingStatus;
	private double adjustQtty;
	private double referenceStatus;
	private double adjustRate;
	private double dividentRate;
	private double status;
	private double totalRoom;
	private double currentRoom;
	private double basicPrice;
	private double openPrice;
	private double closePrice;
	private double currentPrice;
	private double currentQtty;
	private double highestPrice;
	private double lowestPrice;
	private double ceilingPrice;
	private double floorPrice;
	private double totalOfferQtty;
	private double totalBidQtty;
	private double priorPrice;
	private double priorClosePrice;
	private double matchPrice;
	private double matchQtty;
	private double matchValue;
	private double averagePrice;
	private double indexPrice;
	private double bidPrice01;
	private double bidQtty01;
	private double bidPrice02;
	private double bidQtty02;
	private double bidPrice03;
	private double bidQtty03;
	private double offerPrice01;
	private double offerQtty01;
	private double offerPrice02;
	private double offerQtty02;
	private double offerPrice03;
	private double offerQtty03;
	private double prevPriorPrice;
	private double yieldmat;
	private double totalTradeQtty;

	/* extra information */
	private double chgIndex;
	private double pctIndex;
	private double volumeIndex;
	private double currentIndex;
	private String symbol;

	// Constructors

	/** default constructor */
	public SecInfo() {
	}

	public void convertSecInfo(vn.com.vndirect.wsclient.streamquotes.SecInfo secInfoClient) {
		this.currentIndex = secInfoClient.getCurrentIndex();
		this.chgIndex = secInfoClient.getChgIndex();

	}

	/** full constructor */
	public SecInfo(String floorCode, double dateNo, Date tradingDate, String time, double stockId, String code, double stockType, double totalListingQtty, double tradingUnit, double listtingStatus,
			double adjustQtty, double referenceStatus, double adjustRate, double dividentRate, double status, double totalRoom, double currentRoom, double basicPrice, double openPrice,
			double closePrice, double currentPrice, double currentQtty, double highestPrice, double lowestPrice, double ceilingPrice, double floorPrice, double totalOfferQtty, double totalBidQtty,
			double priorPrice, double priorClosePrice, double matchPrice, double matchQtty, double matchValue, double averagePrice, double indexPrice, double bidPrice01, double bidQtty01,
			double bidPrice02, double bidQtty02, double bidPrice03, double bidQtty03, double offerPrice01, double offerQtty01, double offerPrice02, double offerQtty02, double offerPrice03,
			double offerQtty03, double prevPriorPrice, double yieldmat) {
		this.floorCode = floorCode;
		this.dateNo = dateNo;
		this.tradingDate = tradingDate;
		this.time = time;
		this.stockId = stockId;
		this.code = code;
		this.stockType = stockType;
		this.totalListingQtty = totalListingQtty;
		this.tradingUnit = tradingUnit;
		this.listtingStatus = listtingStatus;
		this.adjustQtty = adjustQtty;
		this.referenceStatus = referenceStatus;
		this.adjustRate = adjustRate;
		this.dividentRate = dividentRate;
		this.status = status;
		this.totalRoom = totalRoom;
		this.currentRoom = currentRoom;
		this.basicPrice = basicPrice;
		this.openPrice = openPrice;
		this.closePrice = closePrice;
		this.currentPrice = currentPrice;
		this.currentQtty = currentQtty;
		this.highestPrice = highestPrice;
		this.lowestPrice = lowestPrice;
		this.ceilingPrice = ceilingPrice;
		this.floorPrice = floorPrice;
		this.totalOfferQtty = totalOfferQtty;
		this.totalBidQtty = totalBidQtty;
		this.priorPrice = priorPrice;
		this.priorClosePrice = priorClosePrice;
		this.matchPrice = matchPrice;
		this.matchQtty = matchQtty;
		this.matchValue = matchValue;
		this.averagePrice = averagePrice;
		this.indexPrice = indexPrice;
		this.bidPrice01 = bidPrice01;
		this.bidQtty01 = bidQtty01;
		this.bidPrice02 = bidPrice02;
		this.bidQtty02 = bidQtty02;
		this.bidPrice03 = bidPrice03;
		this.bidQtty03 = bidQtty03;
		this.offerPrice01 = offerPrice01;
		this.offerQtty01 = offerQtty01;
		this.offerPrice02 = offerPrice02;
		this.offerQtty02 = offerQtty02;
		this.offerPrice03 = offerPrice03;
		this.offerQtty03 = offerQtty03;
		this.prevPriorPrice = prevPriorPrice;
		this.yieldmat = yieldmat;
	}

	// Property accessors

	public String getFloorCode() {
		return this.floorCode;
	}

	public void setFloorCode(String floorCode) {
		this.floorCode = floorCode;
	}

	public double getDateNo() {
		return this.dateNo;
	}

	public void setDateNo(double dateNo) {
		this.dateNo = dateNo;
	}

	public Date getTradingDate() {
		return this.tradingDate;
	}

	public void setTradingDate(Date tradingDate) {
		this.tradingDate = tradingDate;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public double getStockId() {
		return this.stockId;
	}

	public void setStockId(double stockId) {
		this.stockId = stockId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public double getStockType() {
		return this.stockType;
	}

	public void setStockType(double stockType) {
		this.stockType = stockType;
	}

	public double getTotalListingQtty() {
		return this.totalListingQtty;
	}

	public void setTotalListingQtty(double totalListingQtty) {
		this.totalListingQtty = totalListingQtty;
	}

	public double getTradingUnit() {
		return this.tradingUnit;
	}

	public void setTradingUnit(double tradingUnit) {
		this.tradingUnit = tradingUnit;
	}

	public double getListtingStatus() {
		return this.listtingStatus;
	}

	public void setListtingStatus(double listtingStatus) {
		this.listtingStatus = listtingStatus;
	}

	public double getAdjustQtty() {
		return this.adjustQtty;
	}

	public void setAdjustQtty(double adjustQtty) {
		this.adjustQtty = adjustQtty;
	}

	public double getReferenceStatus() {
		return this.referenceStatus;
	}

	public void setReferenceStatus(double referenceStatus) {
		this.referenceStatus = referenceStatus;
	}

	public double getAdjustRate() {
		return this.adjustRate;
	}

	public void setAdjustRate(double adjustRate) {
		this.adjustRate = adjustRate;
	}

	public double getDividentRate() {
		return this.dividentRate;
	}

	public void setDividentRate(double dividentRate) {
		this.dividentRate = dividentRate;
	}

	public double getStatus() {
		return this.status;
	}

	public void setStatus(double status) {
		this.status = status;
	}

	public double getTotalRoom() {
		return this.totalRoom;
	}

	public void setTotalRoom(double totalRoom) {
		this.totalRoom = totalRoom;
	}

	public double getCurrentRoom() {
		return this.currentRoom;
	}

	public void setCurrentRoom(double currentRoom) {
		this.currentRoom = currentRoom;
	}

	public double getBasicPrice() {
		return this.basicPrice;
	}

	public void setBasicPrice(double basicPrice) {
		this.basicPrice = basicPrice;
	}

	public double getOpenPrice() {
		return this.openPrice;
	}

	public void setOpenPrice(double openPrice) {
		this.openPrice = openPrice;
	}

	public double getClosePrice() {
		return this.closePrice;
	}

	public void setClosePrice(double closePrice) {
		this.closePrice = closePrice;
	}

	public double getCurrentPrice() {
		return this.currentPrice;
	}

	public void setCurrentPrice(double currentPrice) {
		this.currentPrice = currentPrice;
	}

	public double getCurrentQtty() {
		return this.currentQtty;
	}

	public void setCurrentQtty(double currentQtty) {
		this.currentQtty = currentQtty;
	}

	public double getHighestPrice() {
		return this.highestPrice;
	}

	public void setHighestPrice(double highestPrice) {
		this.highestPrice = highestPrice;
	}

	public double getLowestPrice() {
		return this.lowestPrice;
	}

	public void setLowestPrice(double lowestPrice) {
		this.lowestPrice = lowestPrice;
	}

	public double getCeilingPrice() {
		return this.ceilingPrice;
	}

	public void setCeilingPrice(double ceilingPrice) {
		this.ceilingPrice = ceilingPrice;
	}

	public double getFloorPrice() {
		return this.floorPrice;
	}

	public void setFloorPrice(double floorPrice) {
		this.floorPrice = floorPrice;
	}

	public double getTotalOfferQtty() {
		return this.totalOfferQtty;
	}

	public void setTotalOfferQtty(double totalOfferQtty) {
		this.totalOfferQtty = totalOfferQtty;
	}

	public double getTotalBidQtty() {
		return this.totalBidQtty;
	}

	public void setTotalBidQtty(double totalBidQtty) {
		this.totalBidQtty = totalBidQtty;
	}

	public double getPriorPrice() {
		return this.priorPrice;
	}

	public void setPriorPrice(double priorPrice) {
		this.priorPrice = priorPrice;
	}

	public double getPriorClosePrice() {
		return this.priorClosePrice;
	}

	public void setPriorClosePrice(double priorClosePrice) {
		this.priorClosePrice = priorClosePrice;
	}

	public double getMatchPrice() {
		return this.matchPrice;
	}

	public void setMatchPrice(double matchPrice) {
		this.matchPrice = matchPrice;
	}

	public double getMatchQtty() {
		return this.matchQtty;
	}

	public void setMatchQtty(double matchQtty) {
		this.matchQtty = matchQtty;
	}

	public double getMatchValue() {
		return this.matchValue;
	}

	public void setMatchValue(double matchValue) {
		this.matchValue = matchValue;
	}

	public double getAveragePrice() {
		return this.averagePrice;
	}

	public void setAveragePrice(double averagePrice) {
		this.averagePrice = averagePrice;
	}

	public double getIndexPrice() {
		return this.indexPrice;
	}

	public void setIndexPrice(double indexPrice) {
		this.indexPrice = indexPrice;
	}

	public double getBidPrice01() {
		return this.bidPrice01;
	}

	public void setBidPrice01(double bidPrice01) {
		this.bidPrice01 = bidPrice01;
	}

	public double getBidQtty01() {
		return this.bidQtty01;
	}

	public void setBidQtty01(double bidQtty01) {
		this.bidQtty01 = bidQtty01;
	}

	public double getBidPrice02() {
		return this.bidPrice02;
	}

	public void setBidPrice02(double bidPrice02) {
		this.bidPrice02 = bidPrice02;
	}

	public double getBidQtty02() {
		return this.bidQtty02;
	}

	public void setBidQtty02(double bidQtty02) {
		this.bidQtty02 = bidQtty02;
	}

	public double getBidPrice03() {
		return this.bidPrice03;
	}

	public void setBidPrice03(double bidPrice03) {
		this.bidPrice03 = bidPrice03;
	}

	public double getBidQtty03() {
		return this.bidQtty03;
	}

	public void setBidQtty03(double bidQtty03) {
		this.bidQtty03 = bidQtty03;
	}

	public double getOfferPrice01() {
		return this.offerPrice01;
	}

	public void setOfferPrice01(double offerPrice01) {
		this.offerPrice01 = offerPrice01;
	}

	public double getOfferQtty01() {
		return this.offerQtty01;
	}

	public void setOfferQtty01(double offerQtty01) {
		this.offerQtty01 = offerQtty01;
	}

	public double getOfferPrice02() {
		return this.offerPrice02;
	}

	public void setOfferPrice02(double offerPrice02) {
		this.offerPrice02 = offerPrice02;
	}

	public double getOfferQtty02() {
		return this.offerQtty02;
	}

	public void setOfferQtty02(double offerQtty02) {
		this.offerQtty02 = offerQtty02;
	}

	public double getOfferPrice03() {
		return this.offerPrice03;
	}

	public void setOfferPrice03(double offerPrice03) {
		this.offerPrice03 = offerPrice03;
	}

	public double getOfferQtty03() {
		return this.offerQtty03;
	}

	public void setOfferQtty03(double offerQtty03) {
		this.offerQtty03 = offerQtty03;
	}

	public double getPrevPriorPrice() {
		return this.prevPriorPrice;
	}

	public void setPrevPriorPrice(double prevPriorPrice) {
		this.prevPriorPrice = prevPriorPrice;
	}

	public double getYieldmat() {
		return this.yieldmat;
	}

	public void setYieldmat(double yieldmat) {
		this.yieldmat = yieldmat;
	}

	public double getTotalTradeQtty() {
		return totalTradeQtty;
	}

	public void setTotalTradeQtty(double totalTradeQtty) {
		this.totalTradeQtty = totalTradeQtty;
	}

	/**
	 * @return the chgIndex
	 */
	public double getChgIndex() {
		return this.chgIndex;
	}

	/**
	 * @param chgIndex
	 *            the chgIndex to set
	 */
	public void setChgIndex(double chgIndex) {
		this.chgIndex = chgIndex;
	}

	/**
	 * @return the pctIndex
	 */
	public double getPctIndex() {
		return this.pctIndex;
	}

	/**
	 * @param pctIndex
	 *            the pctIndex to set
	 */
	public void setPctIndex(double pctIndex) {
		this.pctIndex = pctIndex;
	}

	/**
	 * @return the volumeIndex
	 */
	public double getVolumeIndex() {
		return this.volumeIndex;
	}

	/**
	 * @param volumeIndex
	 *            the volumeIndex to set
	 */
	public void setVolumeIndex(double volumeIndex) {
		this.volumeIndex = volumeIndex;
	}

	/**
	 * @return the currentIndex
	 */
	public double getCurrentIndex() {
		return this.currentIndex;
	}

	/**
	 * @param currentIndex
	 *            the currentIndex to set
	 */
	public void setCurrentIndex(double currentIndex) {
		this.currentIndex = currentIndex;
	}

	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}
}